<?php

//add_action('init', 'js_inc_function');
add_action( 'after_setup_theme', 'pmc_musica_theme_setup' );

function pmc_musica_theme_setup() {

	/*woocommerce support*/
	add_theme_support('woocommerce'); // so they don't advertise their themes :)

	/*post formats support*/
	add_theme_support( 'post-formats', array( 'link', 'gallery', 'video' , 'audio') );

	/*feed support*/
	add_theme_support( 'automatic-feed-links' );

	/*post thumb support*/
	add_theme_support( 'post-thumbnails' ); // this enable thumbnails and stuffs

	/*setting thumb size*/
	add_image_size( 'shop', 230 , 230, true );
	add_image_size( 'blog', 580 ,280, true );
	add_image_size( 'gallery', 95 ,95, true );	
	add_image_size( 'related', 146 ,83, true );	
	add_image_size( 'widget', 85 ,55, true );
	add_image_size( 'port4', 230 ,133, true );		
	add_image_size( 'port3', 310 ,230, true );	
	add_image_size( 'port2', 230 ,150, true );	
	add_image_size( 'singlePort', 610 ,610, true );		
	
	/*register custom menus*/
	register_nav_menus(array(

        'main-menu' => 'Main Menu',

        'footer-menu' => 'Footer Menu',
		
		'top_menu' => 'Top Menu',	

		'resp_menu' => 'Responsive Menu'			
			
	));
	
    register_sidebar(array(
        'id' => 'sidebar',
        'name' => 'Sidebar Widget',
        'before_widget' => '<div class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3>',
        'after_title' => '</h3><div class="borderLine sidebar"><div class="borderLineLeft"></div><div class="borderLineRight"></div></div>'
    ));		    		
	
	register_sidebar(array(
	'id' => 'sidebar_category',
	'name' => 'Sidebar Category Widget',
	'before_widget' => '<div class="widget %2$s">',
	'after_widget' => '</div>',
	'before_title' => '<h3>',
	'after_title' => '</h3><div class="borderLine sidebar"><div class="borderLineLeft"></div><div class="borderLineRight"></div></div>' 	));	

	register_sidebar(array(        		
	'id' => 'sidebar_category_top',        		
	'name' => 'Sidebar Category Top Widget',
	'before_widget' => '<div class="widget %2$s">',
	'after_widget' => '</div>',
	'before_title' => '<h3>', 
	'after_title' => '</h3>'    	));	
    
    register_sidebar(array(
        'id' => 'footer1',
        'name' => 'Footer Widget 1',
        'before_widget' => '<div class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3>',
        'after_title' => '</h3>'
    ));
    
    register_sidebar(array(
        'id' => 'footer2',
        'name' => 'Footer Widget 2',
        'before_widget' => '<div class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3>',
        'after_title' => '</h3>'
    ));
    
    register_sidebar(array(
        'id' => 'footer3',
        'name' => 'Footer Widget 3',
        'before_widget' => '<div class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3>',
        'after_title' => '</h3>'
    ));
    
    register_sidebar(array(
        'id' => 'footer4',
        'name' => 'Footer Widget 4',
        'before_widget' => '<div class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3>',
        'after_title' => '</h3>'
    ));
	
	// Responsive walker menu
	class pmc_Walker_Responsive_Menu extends Walker_Nav_Menu {

		
		function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0) {
			global $wp_query;		
			$item_output = $attributes = $prepend ='';
			// Create a visual indent in the list if we have a child item.
			$visual_indent = ( $depth ) ? str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-circle"></i>', $depth) : '';

			// Load the item URL
			$attributes .= ! empty( $item->url ) ? ' href="'   . esc_attr( $item->url ) .'"' : '';

			// If we have hierarchy for the item, add the indent, if not, leave it out.
			// Loop through and output each menu item as this.
			if($depth != 0) {
				$item_output .= '<a ' . $attributes .'>&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-circle"></i>' . $item->title. '</a><br>';
			} else {
				$item_output .= '<a ' . $attributes .'>'.$prepend.$item->title.'</a><br>';
			}


			// Make the output happen.
			$output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );
		}
	}
	
	
	// Main walker menu	
	class pmc_Walker_Main_Menu extends Walker_Nav_Menu
	{
		  function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0) {
			   global $wp_query;
			   $indent = ( $depth ) ? str_repeat( "\t", $depth ) : '';
			   $class_names = $value = '';
			   $classes = empty( $item->classes ) ? array() : (array) $item->classes;
			   $class_names = join( ' ', apply_filters( 'nav_menu_css_class', array_filter( $classes ), $item ) );
			   $class_names = ' class="'. esc_attr( $class_names ) . '"';
			   $output .= $indent . '<li id="menu-item-'.rand(0,9999).'-'. $item->ID . '"' . $value . $class_names .'>';
			   $attributes  = ! empty( $item->attr_title ) ? ' title="'  . esc_attr( $item->attr_title ) .'"' : '';
			   $attributes .= ! empty( $item->target )     ? ' target="' . esc_attr( $item->target     ) .'"' : '';
			   $attributes .= ! empty( $item->xfn )        ? ' rel="'    . esc_attr( $item->xfn        ) .'"' : '';
			   $attributes .= ! empty( $item->url )        ? ' href="'   . esc_attr( $item->url        ) .'"' : '';
			   $prepend = '<strong>';
			   $append = '</strong>';
			   if($depth != 0)
			   {
					$append = $prepend = "";
			   }
				$item_output = $args->before;
				$item_output .= '<a'. $attributes .'>';
				$item_output .= $args->link_before .$prepend.apply_filters( 'the_title', $item->title, $item->ID ).$append;
				$item_output .= $args->link_after;
				$item_output .= '</a>';	
				$item_output .= $args->after;
				$output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );
		}
	}

}



/*-----------------------------------------------------------------------------------*/
// Options Framework
/*-----------------------------------------------------------------------------------*/


// Paths to admin functions
define('MY_TEXTDOMAIN', 'wp-musica');
load_theme_textdomain( 'wp-musica', get_template_directory() . '/languages' );
load_theme_textdomain( 'woocommerce', get_template_directory() . '/languages' );
define('ADMIN_PATH', get_stylesheet_directory() . '/admin/');
define('BOX_PATH', get_stylesheet_directory() . '/includes/boxes/');
define('ADMIN_DIR', get_template_directory_uri() . '/admin/');
define('LAYOUT_PATH', ADMIN_PATH . '/layouts/');

// You can mess with these 2 if you wish.
$themedata = wp_get_theme(get_stylesheet_directory() . '/style.css');
define('THEMENAME', $themedata['Name']);
define('OPTIONS', 'of_options_musica_pmc'); // Name of the database row where your options are stored

if (is_admin() && isset($_GET['activated'] ) && $pagenow == "themes.php" ) {
	//Call action that sets
	
	add_action('admin_head','of_option_setup');

}


function of_option_setup()	{


		
	if (!get_option('of_options_musica_pmc')){
	
		$data = 'YToxMzg6e3M6MTQ6InNob3dyZXNwb25zaXZlIjtzOjE6IjEiO3M6MTM6InNob3dhZHZlcnRpc2UiO3M6MToiMSI7czoxNToiaW5mb3RleHRfc3RhdHVzIjtzOjE6IjEiO3M6MTA6ImJveF9zdGF0dXMiO3M6MToiMSI7czoxODoiaG9tZV9yZWNlbnRfbnVtYmVyIjtzOjE6IjkiO3M6MjY6ImhvbWVfcmVjZW50X251bWJlcl9kaXNwbGF5IjtzOjE6IjMiO3M6MTM6InJhY2VudF9zdGF0dXMiO3M6MToiMSI7czozMToiaG9tZV9yZWNlbnRfbnVtYmVyX2Rpc3BsYXlfcG9zdCI7czoxOiIzIjtzOjIzOiJob21lX3JlY2VudF9udW1iZXJfcG9zdCI7czoyOiIxMCI7czoxNjoiaG9lbXJlY2VudGRlc2lnbiI7czoxOiIxIjtzOjEwOiJjYXR3b290eXBlIjtzOjE6IjEiO3M6MTE6ImFkZF90b19jYXJ0IjtzOjE6IjEiO3M6MjE6InJhY2VudF9zdGF0dXNfcHJvZHVjdCI7czoxOiIxIjtzOjI3OiJob21lX3JlY2VudF9wcm9kdWN0c19udW1iZXIiO3M6MjoiMTYiO3M6MzQ6ImhvbWVfcmVjZW50X251bWJlcl9kaXNwbGF5X3Byb2R1Y3QiO3M6MToiOCI7czoyMjoicmFjZW50X3N0YXR1c19wcm9kdWN0RiI7czoxOiIxIjtzOjI4OiJob21lX3JlY2VudF9wcm9kdWN0c0ZfbnVtYmVyIjtzOjI6IjEyIjtzOjM1OiJob21lX3JlY2VudF9udW1iZXJfZGlzcGxheV9mcHJvZHVjdCI7czoxOiI0IjtzOjE2OiJ0cmFuc2xhdGlvbl9jYXJ0IjtzOjQ6IkNhcnQiO3M6MjU6InRyYW5zbGF0aW9uX3NoYXJlX3Byb2R1Y3QiO3M6MTg6IlNoYXJlIHRoaXMgcHJvZHVjdCI7czoxODoidHJhbnNsYXRpb25fc2FtcGxlIjtzOjExOiJMaXZlIFNhbXBsZSI7czoyMToidHJhbnNsYXRpb25fYWxzb19saWtlIjtzOjE5OiJZb3UgbWlnaHQgYWxzbyBsaWtlIjtzOjI2OiJ0cmFuc2xhdGlvbl9sb2dpbl9yZWdpc3RlciI7czoxNjoiTG9naW4gLyBSZWdpc3RlciI7czoyMDoidHJhbnNsYXRpb25fZmVhdHVyZWQiO3M6Mjc6IkZlYXR1cmVkIFByb2R1Y3RzIGluIE11c2ljYSI7czozMjoidHJhbnNsYXRpb25fcmVjZW50X3BydWR1Y3RfdGl0bGUiO3M6MjU6IlJlY2VudCBBcnJpdmFscyBpbiBNdXNpY2EiO3M6ODoid29vX3pvb20iO3M6MToiMSI7czoxNjoicHJvZHVjdF9jYXRfcGFnZSI7czoyOiIxMiI7czoxODoiY2F0YWxvZ19pbWdfaGVpZ2h0IjtzOjM6IjIzMCI7czo4OiJpbmZvdGV4dCI7czo1NjoiV2VsY29tZSB0byA8c3Bhbj5NVVNJQ0E8L3NwYW4+IC0gQ2hlY2sgb3VyIENEIENvbGxlY3Rpb24iO3M6MTk6InF1b3RlX2JvdHRvbV9ib3JkZXIiO3M6MToiMSI7czoxMDoiYm94MV90aXRsZSI7czoyMzoiQ0hFQ0sgT1VSIENEIENPTExFQ1RJT04iO3M6MTA6ImJveDFfaW1hZ2UiO3M6Njk6Imh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvY2RJY29uLnBuZyI7czo5OiJib3gxX2xpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxNjoiYm94MV9kZXNjcmlwdGlvbiI7czoxMDU6IjxzdHJvbmc+RG9uZWMgcGVkZTwvc3Ryb25nPiBqdXN0bywgZnJpbmdpbGxhIHZlbCwgYWwsIHZ1bHB1dGF0ZSANCmVnZXQsIGFyY3UuIEluIGVuaW0ganVzdG8sIGxvcmVtIGlwc3VtLiI7czoxMDoiYm94MV9jb2xvciI7czo3OiIjMWUxZTIwIjtzOjEwOiJib3gyX3RpdGxlIjtzOjIyOiJMSVNURU4gQkVGT1JFIFBVUkNIQVNFIjtzOjEwOiJib3gyX2ltYWdlIjtzOjc2OiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL2hlYWRQaG9uZUljb24ucG5nIjtzOjk6ImJveDJfbGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjE2OiJib3gyX2Rlc2NyaXB0aW9uIjtzOjEwNToiPHN0cm9uZz5Eb25lYyBwZWRlPC9zdHJvbmc+IGp1c3RvLCBmcmluZ2lsbGEgdmVsLCBhbCwgdnVscHV0YXRlIA0KZWdldCwgYXJjdS4gSW4gZW5pbSBqdXN0bywgbG9yZW0gaXBzdW0uIjtzOjEwOiJib3gyX2NvbG9yIjtzOjc6IiNjYzMzMzMiO3M6MTA6ImJveDNfdGl0bGUiO3M6MTU6IlVQQ09NSU5HIEVWRU5UUyI7czoxMDoiYm94M19pbWFnZSI7czo3MjoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9ldmVudEljb24ucG5nIjtzOjk6ImJveDNfbGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjE2OiJib3gzX2Rlc2NyaXB0aW9uIjtzOjEwNToiPHN0cm9uZz5Eb25lYyBwZWRlPC9zdHJvbmc+IGp1c3RvLCBmcmluZ2lsbGEgdmVsLCBhbCwgdnVscHV0YXRlIA0KZWdldCwgYXJjdS4gSW4gZW5pbSBqdXN0bywgbG9yZW0gaXBzdW0uIjtzOjEwOiJib3gzX2NvbG9yIjtzOjc6IiMxZTFlMjAiO3M6MTQ6ImFkdmVydGlzZWltYWdlIjthOjY6e2k6MTthOjQ6e3M6NToib3JkZXIiO3M6MToiMSI7czo1OiJ0aXRsZSI7czo5OiJTcG9uc29yIDIiO3M6MzoidXJsIjtzOjcxOiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3Nwb25zb3IyLnBuZyI7czo0OiJsaW5rIjtzOjI0OiJodHRwOi8vcHJlbWl1bWNvZGluZy5jb20iO31pOjI7YTo0OntzOjU6Im9yZGVyIjtzOjE6IjIiO3M6NToidGl0bGUiO3M6OToiU3BvbnNvciAzIjtzOjM6InVybCI7czo3MToiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS9zcG9uc29yMy5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9aTozO2E6NDp7czo1OiJvcmRlciI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjk6IlNwb25zb3IgNCI7czozOiJ1cmwiO3M6NzE6Imh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3BvbnNvcjQucG5nIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7fWk6NDthOjQ6e3M6NToib3JkZXIiO3M6MToiNCI7czo1OiJ0aXRsZSI7czo5OiJTcG9uc29yIDUiO3M6MzoidXJsIjtzOjcxOiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3Nwb25zb3I2LnBuZyI7czo0OiJsaW5rIjtzOjI0OiJodHRwOi8vcHJlbWl1bWNvZGluZy5jb20iO31pOjU7YTo0OntzOjU6Im9yZGVyIjtzOjE6IjUiO3M6NToidGl0bGUiO3M6OToiU3BvbnNvciA2IjtzOjM6InVybCI7czo3MToiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS9zcG9uc29yOS5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9aTo2O2E6NDp7czo1OiJvcmRlciI7czoxOiI2IjtzOjU6InRpdGxlIjtzOjk6IlNwb25zb3IgNyI7czozOiJ1cmwiO3M6NzM6Imh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3BvbnNvci0xMC5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9fXM6NDoibG9nbyI7czo3MzoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9tdXNpY2FMb2dvLnBuZyI7czo3OiJmYXZpY29uIjtzOjc3OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L2Zhdmljb24tbWVyY29yLnBuZyI7czoxNjoiZ29vZ2xlX2FuYWx5dGljcyI7czo1NDg6IjxzY3JpcHQgdHlwZT1cInRleHQvamF2YXNjcmlwdFwiPg0KDQogIHZhciBfZ2FxID0gX2dhcSB8fCBbXTsNCiAgX2dhcS5wdXNoKFtcXFwnX3NldEFjY291bnRcXFwnLCBcXFwnVUEtODY5MzQ4Ni0yOVxcXCddKTsNCiAgX2dhcS5wdXNoKFtcXFwnX3RyYWNrUGFnZXZpZXdcXFwnXSk7DQoNCiAgKGZ1bmN0aW9uKCkgew0KICAgIHZhciBnYSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoXFxcJ3NjcmlwdFxcXCcpOyBnYS50eXBlID0gXFxcJ3RleHQvamF2YXNjcmlwdFxcXCc7IGdhLmFzeW5jID0gdHJ1ZTsNCiAgICBnYS5zcmMgPSAoXFxcJ2h0dHBzOlxcXCcgPT0gZG9jdW1lbnQubG9jYXRpb24ucHJvdG9jb2wgPyBcXFwnaHR0cHM6Ly9zc2xcXFwnIDogXFxcJ2h0dHA6Ly93d3dcXFwnKSArIFxcXCcuZ29vZ2xlLWFuYWx5dGljcy5jb20vZ2EuanNcXFwnOw0KICAgIHZhciBzID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXFxcJ3NjcmlwdFxcXCcpWzBdOyBzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKGdhLCBzKTsNCiAgfSkoKTsNCg0KPC9zY3JpcHQ+IjtzOjk6Im1haW5Db2xvciI7czo3OiIjY2MzMzMzIjtzOjg6ImJveENvbG9yIjtzOjc6IiMxZTFlMjAiO3M6MTU6IlNoYWRvd0NvbG9yRm9udCI7czo3OiIjMDAwMDAwIjtzOjIzOiJTaGFkb3dPcGFjaXR0eUNvbG9yRm9udCI7czozOiIwLjIiO3M6MjE6ImJvZHlfYmFja2dyb3VuZF9jb2xvciI7czo3OiIjZmFmYWZhIjtzOjE2OiJiYWNrZ3JvdW5kX2ltYWdlIjtzOjE6IjEiO3M6MTg6ImJvZHlfYmdfcHJvcGVydGllcyI7czoxMDoicmVwZWF0IDAgMCI7czoyMzoiYmFja2dyb3VuZF9pbWFnZV9oZWFkZXIiO3M6MToiMSI7czoyMzoiaGVhZGVyX2JhY2tncm91bmRfY29sb3IiO3M6NzoiIzFlMWUyMCI7czoyMDoiaGVhZGVyX2JnX3Byb3BlcnRpZXMiO3M6MTA6InJlcGVhdCAwIDAiO3M6MTI6ImN1c3RvbV9zdHlsZSI7czozMToiLnJlbGF0ZWQucHJvZHVjdHN7ZGlzcGxheTpub25lfSI7czo5OiJpb3NzbGlkZXIiO2E6NDp7aToxO2E6NTp7czo1OiJvcmRlciI7czoxOiIxIjtzOjU6InRpdGxlIjtzOjUyOiJNVVNJQyBFVkVOVCBXSVRIIERKIFNUQVJUSU5HIEFUIDIwLjAwIE9OIEFVR1VTVCAxNVRIIjtzOjM6InVybCI7czo4NDoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS93b21hbi1zaHVmZmxpbmctdGFibGUuanBnIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6NjgwOiJXZWxjb21lIHRvIG91ciBtYWpvciBldmVudCB0aGF0IHdpbGwgdGFrZSBwbGFjZSBpbiBvdXIgYmFyLCBiZXNpZGVzIG91ciBTdG9yZS4gVGhlcmUgd2lsbCBiZSBzZXZlcmFsIHJlbm93bmVkIHBlcmZvcm1lcyB0aGF0IHdpbGwgdGFrZSBjYXJlIG9mIHlvdXIgZWFycywgc29tZSBhcmUgbGlzdGVkIGJlbG93Og0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5KT0hOIERPRTwvaDM+IC0gTWl4IEFtYXppbmcgRWxla3RybyBTb3VuZA0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5KQU5FIERPRTwvaDM+IC0gQmVzdCBESiBpbiBUb3duDQo8YnI+PGJyPg0KPGgzIHN0eWxlID0gXCJjb2xvcjojZmZmO21hcmdpbjowO1wiPkNBVEhFUklORSBET0U8L2gzPiAtIFdvcmtpbmcgdXAgdGhlIEJlYXQNCjxicj48YnI+DQo8aDMgc3R5bGUgPSBcImNvbG9yOiNmZmY7bWFyZ2luOjA7XCI+R0xKSVZFQzwvaDM+IC0gV29ya2luZyBkb3duIHRoZSBCZWF0DQo8YnI+PGJyPg0KRXZlbnQgd2lsbCBzdGFydCBhdCA4cG0uIElmIHlvdSBoYXZlIGFueSBxdWVzdGlvbnMgYWJvdXQgdGhlIEV2ZW50IG9yIHRoaXMgVGVtcGxhdGUsIHlvdSBjYW4gYXNrIHVzIGF0IDxzdHJvbmc+c3VwcG9ydEBwcmVtaXVtY29kaW5nLmNvbTwvc3Ryb25nPiA6KSI7fWk6MjthOjU6e3M6NToib3JkZXIiO3M6MToiMiI7czo1OiJ0aXRsZSI7czozOToiTElWRSBDT05DRVJUIFdJVEggQSBSRU5PV05FRCBST0NLIEdST1VQIjtzOjM6InVybCI7czo5ODoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9waG90b2R1bmUtMjc3MzA3LXJvY2stY29uY2VydC1zbWFsbC5qcGciO3M6NDoibGluayI7czowOiIiO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjA6IiI7fWk6MzthOjU6e3M6NToib3JkZXIiO3M6MToiMyI7czo1OiJ0aXRsZSI7czo0NjoiTklHSFQgQ0xVQiBPUEVOSU5HIFRPTklHSFQgV0lUSCBTUEVDSUFMIEdVRVNUUyI7czozOiJ1cmwiO3M6MTA2OiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3Bob3RvZHVuZS0yMTkxNjMxLWRqLW11c2ljLW5pZ2h0LWNsdWItcy1idzEuanBnIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6NjgwOiJXZWxjb21lIHRvIG91ciBtYWpvciBldmVudCB0aGF0IHdpbGwgdGFrZSBwbGFjZSBpbiBvdXIgYmFyLCBiZXNpZGVzIG91ciBTdG9yZS4gVGhlcmUgd2lsbCBiZSBzZXZlcmFsIHJlbm93bmVkIHBlcmZvcm1lcyB0aGF0IHdpbGwgdGFrZSBjYXJlIG9mIHlvdXIgZWFycywgc29tZSBhcmUgbGlzdGVkIGJlbG93Og0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5KT0hOIERPRTwvaDM+IC0gTWl4IEFtYXppbmcgRWxla3RybyBTb3VuZA0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5KQU5FIERPRTwvaDM+IC0gQmVzdCBESiBpbiBUb3duDQo8YnI+PGJyPg0KPGgzIHN0eWxlID0gXCJjb2xvcjojZmZmO21hcmdpbjowO1wiPkNBVEhFUklORSBET0U8L2gzPiAtIFdvcmtpbmcgdXAgdGhlIEJlYXQNCjxicj48YnI+DQo8aDMgc3R5bGUgPSBcImNvbG9yOiNmZmY7bWFyZ2luOjA7XCI+R0xKSVZFQzwvaDM+IC0gV29ya2luZyBkb3duIHRoZSBCZWF0DQo8YnI+PGJyPg0KRXZlbnQgd2lsbCBzdGFydCBhdCA4cG0uIElmIHlvdSBoYXZlIGFueSBxdWVzdGlvbnMgYWJvdXQgdGhlIEV2ZW50IG9yIHRoaXMgVGVtcGxhdGUsIHlvdSBjYW4gYXNrIHVzIGF0IDxzdHJvbmc+c3VwcG9ydEBwcmVtaXVtY29kaW5nLmNvbTwvc3Ryb25nPiA6KSI7fWk6NDthOjU6e3M6NToib3JkZXIiO3M6MToiNCI7czo1OiJ0aXRsZSI7czo1MzoiTElWRSBHVUlUQVIgQ09OQ0VSVCBXSVRIIFNFVkVSQUwgV0VMTCBLTk9XTiBNVVNJQ0lBTlMiO3M6MzoidXJsIjtzOjc4OiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL2d1aXRhci1jb25jZXJ0MS5qcGciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czowOiIiO319czoxMToiZGVtb19zbGlkZXIiO2E6NDp7aToxO2E6ODp7czo1OiJvcmRlciI7czoxOiIxIjtzOjU6InRpdGxlIjtzOjU6Ik1hc2tzIjtzOjM6InVybCI7czo3NDoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8xMS9lbXB0eUhvbGRlci5wbmciO3M6NToidmlkZW8iO3M6MDoiIjtzOjM6InRvcCI7czoyOiIyNSI7czo0OiJsZWZ0IjtzOjI6IjU3IjtzOjQ6ImxpbmsiO3M6MDoiIjtzOjExOiJkZXNjcmlwdGlvbiI7czoxNzg4OiI8ZGl2IGNsYXNzPVwiY2FwdGlvbkJveFwiIHN0eWxlPVwiaGVpZ2h0OiAyMzVweDsgbWFyZ2luLWxlZnQ6NDBweDsgei1pbmRleDoxMjtcIj4NCjxoMSBjbGFzcz1cInVuZGVybGluZVwiIHN0eWxlPVwicGFkZGluZzogMTVweCAyNXB4IDE1cHggMHB4OyBmb250LXNpemU6IDI2cHggIWltcG9ydGFudDtcIj5MUCBDT0xMRUNUSU9OPC9oMT4NCjx1bCBjbGFzcz1cInF1b3RlXCIgc3R5bGU9XCJwYWRkaW5nLXJpZ2h0OiAyMHB4O1wiPg0KCTxsaSBjbGFzcz1cImxlZnRcIj5Zb3UgY2FuIGFkZCA8c3Ryb25nPnVuaXF1ZSA8L3N0cm9uZz4gaW1hZ2VzPC9saT4NCgk8bGkgY2xhc3M9XCJyaWdodFwiPnRvIGVhY2ggc2xpZGUgYW5kIG1ha2UgdGhlbSA8c3BhbiBzdHlsZT1cImZvbnQtd2VpZ2h0OiBib2xkO1wiPmRpc3RpbmN0Ljwvc3Bhbj48L2xpPg0KCTxsaSBjbGFzcz1cImxlZnRcIj5HZXQgdGhlIGNvbXBsZXRlIDxzcGFuIHN0eWxlPVwiZm9udC13ZWlnaHQ6IGJvbGQ7XCI+ZnJlZWRvbTwvc3Bhbj4gb2YgeW91ciBkZXNpZ24uPC9saT4NCgk8bGkgY2xhc3M9XCJyaWdodFwiPkEgY3JlYXRpdmUgYXBwcm9hY2ggdG8gPHN0cm9uZz53ZWIgZGVzaWduLjwvc3Ryb25nPjwvbGk+DQo8L3VsPg0KPHVsPg0KCTxsaSBjbGFzcz1cImJ1dHRvblwiPjxhIGhyZWY9XCJodHRwOi8vcHJlbWl1bWNvZGluZy5jb21cIj5SRUFEIE1PUkU8L2E+PC9saT4NCjwvdWw+DQo8L2Rpdj4NCg0KPHVsPg0KDQoNCjxsaSBjbGFzcz1cInRvcDFcIj4NCjxhIGhyZWYgPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS9wcm9kdWN0L2JlYXV0aWZ1bC13aGl0ZS1wZWFybHMvXCI+DQo8aW1nIHN0eWxlID0gXCJtYXJnaW46LTExMHB4IDBweCAwIC02MDBweDtcIiBzcmM9XCJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3NsaWRlc2hvdy1pbWFnZS00LnBuZw0KXCIgYWx0PVwiaW1hZ2VcIi8+PC9hPjwvbGk+DQoNCjxsaSBjbGFzcz1cInRvcDJcIj4NCjxhIGhyZWYgPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS9wcm9kdWN0L2Etc3R5bGlzaC1jYXJuaXZhbC1tYXNrL1wiPg0KPGltZyBzdHlsZSA9IFwibWFyZ2luOi0xMTBweCAwcHggMCAtMzYwcHg7XCIgc3JjPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9zbGlkZXNob3ctaW1hZ2UtMy5wbmcNClwiIGFsdD1cImltYWdlXCIvPjwvYT48L2xpPg0KDQo8bGkgY2xhc3M9XCJ0b3AzXCI+DQo8YSBocmVmID1cImh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vcHJvZHVjdC92aW9saW5vLWNvbmNlcnRvL1wiPg0KPGltZyBzdHlsZSA9IFwibWFyZ2luOjEzMHB4IDBweCAwIC02MDBweDtcIiBzcmM9XCJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3NsaWRlc2hvdy1pbWFnZS0yLnBuZw0KXCIgYWx0PVwiaW1hZ2VcIi8+PC9hPjwvbGk+DQoNCjxsaSBjbGFzcz1cInRvcDRcIj4NCjxhIGhyZWYgPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS9wcm9kdWN0L3N0cmFuZ2UtdG8teW91ci1lYXJzL1wiPg0KPGltZyBzdHlsZSA9IFwibWFyZ2luOjEzMHB4IDBweCAwIC0zNjBweDtcIiBzcmM9XCJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3NsaWRlc2hvdy1pbWFnZS0xLnBuZw0KXCIgYWx0PVwiaW1hZ2VcIi8+PC9hPjwvbGk+DQoNCjwvdWw+DQoNCiAiO31pOjI7YTo4OntzOjU6Im9yZGVyIjtzOjE6IjIiO3M6NToidGl0bGUiO3M6NToiVmlkZW8iO3M6MzoidXJsIjtzOjA6IiI7czo1OiJ2aWRlbyI7czozODoiaHR0cDovL3BsYXllci52aW1lby5jb20vdmlkZW8vMjQ0NTY3ODciO3M6MzoidG9wIjtzOjE6IjYiO3M6NDoibGVmdCI7czo0OiI3OS4xIjtzOjQ6ImxpbmsiO3M6MDoiIjtzOjExOiJkZXNjcmlwdGlvbiI7czo2Nzk6IjxkaXYgY2xhc3M9XCJjYXB0aW9uQm94XCIgc3R5bGU9XCJoZWlnaHQ6IDQ0MHB4OyB3aWR0aDoyMDBweDtcIj4NCjxoMSBjbGFzcz1cInVuZGVybGluZVwiIHN0eWxlPVwicGFkZGluZzogMTVweCAyNXB4IDE1cHggMHB4OyBmb250LXNpemU6IDI2cHggIWltcG9ydGFudDtcIj5WSURFT1M8L2gxPg0KPHVsIGNsYXNzPVwicXVvdGVcIiBzdHlsZT1cInBhZGRpbmctcmlnaHQ6IDIwcHg7XCI+DQoJPGxpIGNsYXNzPVwibGVmdFwiPllvdSBjYW4gYWRkIHZpZGVvcw0KCWFuZCBhZGQgZGVzY3JpcHRpb24NCglUZWxsIHlvdXIgdmlzaXRvcnMuDQoJd2hhdCBpdFxcXCdzIGFib3V0Lg0KICAgICAgICBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dWVyIGFkaXBpc2NpbmcgZWxpdCwgc2VkIGRpYW0gbm9udW1teSBuaWJoIGV1aXNtb2QgdGluY2lkdW50IHV0IGxhb3JlZXQgZG9sb3JlIG1hZ25hIGFsaXF1YW0gZXJhdCB2b2x1dHBhdC4gIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ZXIgYWRpcGlzY2luZyBlbGl0LiBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldDwvc3Ryb25nPjwvbGk+DQo8L3VsPg0KDQoJPGxpIGNsYXNzPVwiYnV0dG9uXCI+PGEgaHJlZj1cImh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbVwiPlJFQUQgTU9SRTwvYT48L2xpPg0KDQo8L2Rpdj4iO31pOjM7YTo4OntzOjU6Im9yZGVyIjtzOjE6IjMiO3M6NToidGl0bGUiO3M6NToiSXBhZHMiO3M6MzoidXJsIjtzOjc0OiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzExL2VtcHR5SG9sZGVyLnBuZyI7czo1OiJ2aWRlbyI7czowOiIiO3M6MzoidG9wIjtzOjI6IjI0IjtzOjQ6ImxlZnQiO3M6MjoiNjAiO3M6NDoibGluayI7czowOiIiO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjE0NDQ6Ijx1bD4NCjxsaSBjbGFzcz1cInRvcDJcIiBzdHlsZT1cInotaW5kZXg6OTtcIj4NCjxhIGhyZWYgPVwiaHR0cDovL2RhZWRyYS5wcmVtaXVtY29kaW5nLmNvbVwiPg0KPGltZyBhbHQ9XCJpbWFnZVwiIHN0eWxlID0gXCJtYXJnaW46MjBweCAwcHggMCAtNjg1cHg7XCIgc3JjPVwiaHR0cDovL2RhZWRyYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8xMC9pcGhvbmUucG5nDQpcIi8+PC9hPjwvbGk+DQoNCg0KPGxpIGNsYXNzPVwidG9wMVwiIHN0eWxlPVwiei1pbmRleDo4O1wiPg0KPGEgaHJlZiA9XCJodHRwOi8vZGFlZHJhLnByZW1pdW1jb2RpbmcuY29tXCI+DQo8aW1nIGFsdD1cImltYWdlXCIgc3R5bGUgPSBcIm1hcmdpbjotNjNweCAwcHggMCAtNjIwcHg7XCIgc3JjPVwiaHR0cDovL2RhZWRyYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8xMC9sY2Rtb25pdG9yLnBuZw0KXCIvPjwvYT48L2xpPg0KDQo8bGkgY2xhc3M9XCJ0b3AzXCIgc3R5bGU9XCJ6LWluZGV4OjEwO1wiPg0KPGEgaHJlZiA9XCJodHRwOi8vZGFlZHJhLnByZW1pdW1jb2RpbmcuY29tXCI+DQo8aW1nIGFsdD1cImltYWdlXCIgc3R5bGUgPSBcIm1hcmdpbjoxMDZweCAwcHggMCAtMzMwcHg7XCIgc3JjPVwiaHR0cDovL2RhZWRyYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8xMC9pcGFkLnBuZw0KXCIvPjwvYT48L2xpPg0KDQo8L3VsPg0KDQoNCg0KDQoNCjxkaXYgY2xhc3M9XCJjYXB0aW9uQm94XCIgc3R5bGU9XCJoZWlnaHQ6IDIzNXB4O1wiPg0KPGgxIGNsYXNzPVwidW5kZXJsaW5lXCIgc3R5bGU9XCJwYWRkaW5nOiAxNXB4IDI1cHggMTVweCAwcHg7IGZvbnQtc2l6ZTogMjZweCAhaW1wb3J0YW50O1wiPlVOTElNSVRFRCBJTUFHRVM8L2gxPg0KPHVsIGNsYXNzPVwicXVvdGVcIiBzdHlsZT1cInBhZGRpbmctcmlnaHQ6IDIwcHg7XCI+DQoJPGxpIGNsYXNzPVwibGVmdFwiPllvdSBjYW4gYWRkIDxzdHJvbmc+dW5pcXVlIDwvc3Ryb25nPiB3aWRlIGltYWdlczwvbGk+DQoJPGxpIGNsYXNzPVwicmlnaHRcIj52aWRlb3MgYW5kIGV4dHJhIGltYWdlcyA8c3BhbiBzdHlsZT1cImZvbnQtd2VpZ2h0OiBib2xkO1wiPnRvIHNsaWRlci48L3NwYW4+PC9saT4NCgk8bGkgY2xhc3M9XCJsZWZ0XCI+R2V0IHRoZSBjb21wbGV0ZSA8c3BhbiBzdHlsZT1cImZvbnQtd2VpZ2h0OiBib2xkO1wiPmZyZWVkb208L3NwYW4+IG9mIHlvdXIgZGVzaWduLjwvbGk+DQoJPGxpIGNsYXNzPVwicmlnaHRcIj5BIGNyZWF0aXZlIGFwcHJvYWNoIHRvIDxzdHJvbmc+d2ViIGRlc2lnbi48L3N0cm9uZz48L2xpPg0KPC91bD4NCjx1bD4NCgk8bGkgY2xhc3M9XCJidXR0b25cIj48YSBocmVmPVwiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tXCI+UkVBRCBNT1JFPC9hPjwvbGk+DQo8L3VsPg0KPC9kaXY+DQoiO31pOjQ7YTo4OntzOjU6Im9yZGVyIjtzOjE6IjQiO3M6NToidGl0bGUiO3M6NToiSW1hZ2UiO3M6MzoidXJsIjtzOjcwOiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzExL3JhaWx3YXkuanBnIjtzOjU6InZpZGVvIjtzOjA6IiI7czozOiJ0b3AiO3M6MjoiMjUiO3M6NDoibGVmdCI7czoyOiIyNSI7czo0OiJsaW5rIjtzOjA6IiI7czoxMToiZGVzY3JpcHRpb24iO3M6NjkyOiI8ZGl2IGNsYXNzPVwiY2FwdGlvbkJveFwiIHN0eWxlPVwiaGVpZ2h0OiAyMzVweDtcIj4NCjxoMSBjbGFzcz1cInVuZGVybGluZVwiIHN0eWxlPVwicGFkZGluZzogMTVweCAyNXB4IDE1cHggMHB4OyBmb250LXNpemU6IDI2cHggIWltcG9ydGFudDtcIj5VTkxJTUlURUQgSU1BR0VTPC9oMT4NCjx1bCBjbGFzcz1cInF1b3RlXCIgc3R5bGU9XCJwYWRkaW5nLXJpZ2h0OiAyMHB4O1wiPg0KCTxsaSBjbGFzcz1cImxlZnRcIj5Zb3UgY2FuIGFkZCA8c3Ryb25nPnVuaXF1ZSA8L3N0cm9uZz4gd2lkZSBpbWFnZXM8L2xpPg0KCTxsaSBjbGFzcz1cInJpZ2h0XCI+dmlkZW9zIGFuZCBleHRyYSBpbWFnZXMgPHNwYW4gc3R5bGU9XCJmb250LXdlaWdodDogYm9sZDtcIj50byBzbGlkZXIuPC9zcGFuPjwvbGk+DQoJPGxpIGNsYXNzPVwibGVmdFwiPkdldCB0aGUgY29tcGxldGUgPHNwYW4gc3R5bGU9XCJmb250LXdlaWdodDogYm9sZDtcIj5mcmVlZG9tPC9zcGFuPiBvZiB5b3VyIGRlc2lnbi48L2xpPg0KCTxsaSBjbGFzcz1cInJpZ2h0XCI+QSBjcmVhdGl2ZSBhcHByb2FjaCB0byA8c3Ryb25nPndlYiBkZXNpZ24uPC9zdHJvbmc+PC9saT4NCjwvdWw+DQo8dWw+DQoJPGxpIGNsYXNzPVwiYnV0dG9uXCI+PGEgaHJlZj1cImh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbVwiPlJFQUQgTU9SRTwvYT48L2xpPg0KPC91bD4NCjwvZGl2PiI7fX1zOjExOiJuaXZvX3NsaWRlciI7YTozOntpOjE7YTo1OntzOjU6Im9yZGVyIjtzOjE6IjEiO3M6NToidGl0bGUiO3M6NTI6Ik1VU0lDIEVWRU5UIFdJVEggREogU1RBUlRJTkcgQVQgMjAuMDAgT04gQVVHVVNUIDE1VEgiO3M6MzoidXJsIjtzOjg1OiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3dvbWFuLXNodWZmbGluZy10YWJsZTEuanBnIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6NTI6Ik1VU0lDIEVWRU5UIFdJVEggREogU1RBUlRJTkcgQVQgMjAuMDAgT04gQVVHVVNUIDE1VEgiO31pOjI7YTo1OntzOjU6Im9yZGVyIjtzOjE6IjIiO3M6NToidGl0bGUiO3M6NTM6IkxJVkUgR1VJVEFSIENPTkNFUlQgV0lUSCBTRVZFUkFMIFdFTEwgS05PV04gTVVTSUNJQU5TIjtzOjM6InVybCI7czo3ODoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9ndWl0YXItY29uY2VydDIuanBnIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6NTM6IkxJVkUgR1VJVEFSIENPTkNFUlQgV0lUSCBTRVZFUkFMIFdFTEwgS05PV04gTVVTSUNJQU5TIjt9aTozO2E6NTp7czo1OiJvcmRlciI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjQ2OiJOSUdIVCBDTFVCIE9QRU5JTkcgVE9OSUdIVCBXSVRIIFNQRUNJQUwgR1VFU1RTIjtzOjM6InVybCI7czoxMDY6Imh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvcGhvdG9kdW5lLTIxOTE2MzEtZGotbXVzaWMtbmlnaHQtY2x1Yi1zLWJ3Mi5qcGciO3M6NDoibGluayI7czowOiIiO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjQ2OiJOSUdIVCBDTFVCIE9QRU5JTkcgVE9OSUdIVCBXSVRIIFNQRUNJQUwgR1VFU1RTIjt9fXM6MTQ6InNsaWRlcl9vcGFjaXR5IjtzOjM6IjAuOSI7czo4OiJhbmlzcGVlZCI7czozOiI4MDAiO3M6OToicGF1c2V0aW1lIjtzOjU6IjIwMDAwIjtzOjI1OiJzbGlkZXJfZm9udFNpemVfY29sb3JOaXZvIjthOjI6e3M6NDoic2l6ZSI7czo0OiIyNHB4IjtzOjU6ImNvbG9yIjtzOjc6IiNmZmZmZmYiO31zOjIwOiJzbGlkZXJfYmFja0NvbG9yTml2byI7czo3OiIjY2MzMzMzIjtzOjIyOiJzbGlkZXJfYm9yZGVyQ29sb3JOaXZvIjtzOjc6IiNjYzMzMzMiO3M6NjoiZWZmZWN0IjtzOjY6InJhbmRvbSI7czo2OiJzbGljZXMiO3M6MjoiMTUiO3M6NzoiYm94Y29scyI7czoxOiI4IjtzOjc6ImJveHJvd3MiO3M6MToiNCI7czo5OiJib2R5X2ZvbnQiO2E6Mzp7czo0OiJzaXplIjtzOjQ6IjEzcHgiO3M6NToiY29sb3IiO3M6NzoiIzJhMmIyYyI7czo0OiJmYWNlIjtzOjE0OiJIZWx2ZXRpY2EgTmV1ZSI7fXM6MTI6ImhlYWRpbmdfZm9udCI7YToyOntzOjQ6ImZhY2UiO3M6NjoiT3N3YWxkIjtzOjU6InN0eWxlIjtzOjY6Im5vcm1hbCI7fXM6OToibWVudV9mb250IjtzOjE0OiJIZWx2ZXRpY2EgTmV1ZSI7czoxNDoiYm9keV9ib3hfY29sZXIiO3M6NzoiI2ZmZmZmZiI7czoxNToiYm9keV9saW5rX2NvbGVyIjtzOjc6IiMyYTJiMmMiO3M6MTU6ImhlYWRpbmdfZm9udF9oMSI7YToyOntzOjQ6InNpemUiO3M6NDoiMjhweCI7czo1OiJjb2xvciI7czo3OiIjMmEyYjJjIjt9czoxNToiaGVhZGluZ19mb250X2gyIjthOjI6e3M6NDoic2l6ZSI7czo0OiIyNHB4IjtzOjU6ImNvbG9yIjtzOjc6IiMyYTJiMmMiO31zOjE1OiJoZWFkaW5nX2ZvbnRfaDMiO2E6Mjp7czo0OiJzaXplIjtzOjQ6IjIwcHgiO3M6NToiY29sb3IiO3M6NzoiIzJhMmIyYyI7fXM6MTU6ImhlYWRpbmdfZm9udF9oNCI7YToyOntzOjQ6InNpemUiO3M6NDoiMThweCI7czo1OiJjb2xvciI7czo3OiIjMmEyYjJjIjt9czoxNToiaGVhZGluZ19mb250X2g1IjthOjI6e3M6NDoic2l6ZSI7czo0OiIxN3B4IjtzOjU6ImNvbG9yIjtzOjc6IiMyYTJiMmMiO31zOjE1OiJoZWFkaW5nX2ZvbnRfaDYiO2E6Mjp7czo0OiJzaXplIjtzOjQ6IjE2cHgiO3M6NToiY29sb3IiO3M6NzoiIzJhMmIyYyI7fXM6NDoidGVhbSI7YTo2OntpOjE7YToxMTp7czo1OiJvcmRlciI7czoxOiIxIjtzOjU6InRpdGxlIjtzOjg6IkphbmUgRG9lIjtzOjQ6InJvbGUiO3M6MTk6IlByZXNpZGVudCAmIEZvdW5kZXIiO3M6MzoidXJsIjtzOjc0OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3RlYW1NZW1iZXIxLmpwZyI7czo0OiJpY29uIjtzOjc0OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L2ZvdW5kZXJUZWFtLnBuZyI7czo3OiJ0d2l0dGVyIjtzOjMyOiJodHRwOi8vdHdpdHRlci5jb20vcHJlbWl1bWNvZGluZyI7czo4OiJmYWNlYm9vayI7czozNjoiaHR0cDovL3d3dy5mYWNlYm9vay5jb20vR0ZsYXNoRGVzaWduIjtzOjU6InZpbWVvIjtzOjE2OiJodHRwOi8vdmltZW8uY29tIjtzOjc6ImRyaWJibGUiO3M6Mjc6Imh0dHA6Ly9kcmliYmJsZS5jb20vZ2xqaXZlYyI7czo0OiJtYWlsIjtzOjIyOiJpbmZvQHByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czoyNzE6IjxiPkxvcmVtIGlwc3VtPC9iPiBkb2xvciBzaXQgYW1ldCBkYXMgY29uc2UgDQpuaWJoIGV1aXNtb2RvcyB0aW5jaWR1bnQgdXQgbGFvcmVlIGNvbnNlDQplc3QgYXQuIE51bGxhIHZpdGFlIDxiPmVsaXQgbGliZXJvPC9iPiwgYSBwaGEgc2l0IGFtDQp0ZXR1ZXIgYWRpcGlzY2luZyBlbGl0LiBOdWxsYSB2aXRhZSBlbGl0IGxlcm8sIA0KYSBwaGFyZXRyYS4gPGI+TG9yZW0gaXBzdW08L2I+IGN0ZXR1ZXIgYWRpcGlzY2luZy4gDQpMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldC4iO31pOjI7YToxMTp7czo1OiJvcmRlciI7czoxOiIyIjtzOjU6InRpdGxlIjtzOjg6IkpvaG4gRG9lIjtzOjQ6InJvbGUiO3M6MTM6IldlYiBEZXZlbG9wZXIiO3M6MzoidXJsIjtzOjc0OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3RlYW1NZW1iZXIyLnBuZyI7czo0OiJpY29uIjtzOjc5OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3dlYkRldmVsb3Blckljb24ucG5nIjtzOjc6InR3aXR0ZXIiO3M6MzI6Imh0dHA6Ly90d2l0dGVyLmNvbS9wcmVtaXVtY29kaW5nIjtzOjg6ImZhY2Vib29rIjtzOjM2OiJodHRwOi8vd3d3LmZhY2Vib29rLmNvbS9HRmxhc2hEZXNpZ24iO3M6NToidmltZW8iO3M6MDoiIjtzOjc6ImRyaWJibGUiO3M6Mjc6Imh0dHA6Ly9kcmliYmJsZS5jb20vZ2xqaXZlYyI7czo0OiJtYWlsIjtzOjIyOiJpbmZvQHByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czoyNzE6IjxiPkxvcmVtIGlwc3VtPC9iPiBkb2xvciBzaXQgYW1ldCBkYXMgY29uc2UgDQpuaWJoIGV1aXNtb2RvcyB0aW5jaWR1bnQgdXQgbGFvcmVlIGNvbnNlDQplc3QgYXQuIE51bGxhIHZpdGFlIDxiPmVsaXQgbGliZXJvPC9iPiwgYSBwaGEgc2l0IGFtDQp0ZXR1ZXIgYWRpcGlzY2luZyBlbGl0LiBOdWxsYSB2aXRhZSBlbGl0IGxlcm8sIA0KYSBwaGFyZXRyYS4gPGI+TG9yZW0gaXBzdW08L2I+IGN0ZXR1ZXIgYWRpcGlzY2luZy4gDQpMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldC4iO31pOjM7YToxMTp7czo1OiJvcmRlciI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjEzOiJKb3NlcGhpbmUgRG9lIjtzOjQ6InJvbGUiO3M6MTY6IkN1c3RvbWVyIFNlcnZpY2UiO3M6MzoidXJsIjtzOjc0OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3RlYW1NZW1iZXIzLnBuZyI7czo0OiJpY29uIjtzOjc4OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3N1cHBvcnRUZWFtSWNvbi5wbmciO3M6NzoidHdpdHRlciI7czozMjoiaHR0cDovL3R3aXR0ZXIuY29tL3ByZW1pdW1jb2RpbmciO3M6ODoiZmFjZWJvb2siO3M6MzY6Imh0dHA6Ly93d3cuZmFjZWJvb2suY29tL0dGbGFzaERlc2lnbiI7czo1OiJ2aW1lbyI7czowOiIiO3M6NzoiZHJpYmJsZSI7czowOiIiO3M6NDoibWFpbCI7czoyMjoiaW5mb0BwcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6MjcxOiI8Yj5Mb3JlbSBpcHN1bTwvYj4gZG9sb3Igc2l0IGFtZXQgZGFzIGNvbnNlIA0KbmliaCBldWlzbW9kb3MgdGluY2lkdW50IHV0IGxhb3JlZSBjb25zZQ0KZXN0IGF0LiBOdWxsYSB2aXRhZSA8Yj5lbGl0IGxpYmVybzwvYj4sIGEgcGhhIHNpdCBhbQ0KdGV0dWVyIGFkaXBpc2NpbmcgZWxpdC4gTnVsbGEgdml0YWUgZWxpdCBsZXJvLCANCmEgcGhhcmV0cmEuIDxiPkxvcmVtIGlwc3VtPC9iPiBjdGV0dWVyIGFkaXBpc2NpbmcuIA0KTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQuIjt9aTo0O2E6MTE6e3M6NToib3JkZXIiO3M6MToiNCI7czo1OiJ0aXRsZSI7czo2OiJEYW1pZW4iO3M6NDoicm9sZSI7czo5OiJQSFAgQ29kZXIiO3M6MzoidXJsIjtzOjc0OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3RlYW1NZW1iZXI0LnBuZyI7czo0OiJpY29uIjtzOjc0OiJodHRwOi8vbWVyY29yLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3BocFRlYW1JY29uLnBuZyI7czo3OiJ0d2l0dGVyIjtzOjMyOiJodHRwOi8vdHdpdHRlci5jb20vcHJlbWl1bWNvZGluZyI7czo4OiJmYWNlYm9vayI7czozNjoiaHR0cDovL3d3dy5mYWNlYm9vay5jb20vR0ZsYXNoRGVzaWduIjtzOjU6InZpbWVvIjtzOjA6IiI7czo3OiJkcmliYmxlIjtzOjI3OiJodHRwOi8vZHJpYmJibGUuY29tL2dsaml2ZWMiO3M6NDoibWFpbCI7czoyMjoiaW5mb0BwcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6MjcxOiI8Yj5Mb3JlbSBpcHN1bTwvYj4gZG9sb3Igc2l0IGFtZXQgZGFzIGNvbnNlIA0KbmliaCBldWlzbW9kb3MgdGluY2lkdW50IHV0IGxhb3JlZSBjb25zZQ0KZXN0IGF0LiBOdWxsYSB2aXRhZSA8Yj5lbGl0IGxpYmVybzwvYj4sIGEgcGhhIHNpdCBhbQ0KdGV0dWVyIGFkaXBpc2NpbmcgZWxpdC4gTnVsbGEgdml0YWUgZWxpdCBsZXJvLCANCmEgcGhhcmV0cmEuIDxiPkxvcmVtIGlwc3VtPC9iPiBjdGV0dWVyIGFkaXBpc2NpbmcuIA0KTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQuIjt9aTo1O2E6MTE6e3M6NToib3JkZXIiO3M6MToiNSI7czo1OiJ0aXRsZSI7czoxMzoiQ2hyaXN0aW5hIERvZSI7czo0OiJyb2xlIjtzOjk6Ik1hcmtldGVlciI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvdGVhbU1lbWJlcjUucG5nIjtzOjQ6Imljb24iO3M6ODA6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvbWFya2V0aW5nVGVhbUljb24ucG5nIjtzOjc6InR3aXR0ZXIiO3M6MzI6Imh0dHA6Ly90d2l0dGVyLmNvbS9wcmVtaXVtY29kaW5nIjtzOjg6ImZhY2Vib29rIjtzOjM2OiJodHRwOi8vd3d3LmZhY2Vib29rLmNvbS9HRmxhc2hEZXNpZ24iO3M6NToidmltZW8iO3M6MDoiIjtzOjc6ImRyaWJibGUiO3M6MDoiIjtzOjQ6Im1haWwiO3M6MjI6ImluZm9AcHJlbWl1bWNvZGluZy5jb20iO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjI3MToiPGI+TG9yZW0gaXBzdW08L2I+IGRvbG9yIHNpdCBhbWV0IGRhcyBjb25zZSANCm5pYmggZXVpc21vZG9zIHRpbmNpZHVudCB1dCBsYW9yZWUgY29uc2UNCmVzdCBhdC4gTnVsbGEgdml0YWUgPGI+ZWxpdCBsaWJlcm88L2I+LCBhIHBoYSBzaXQgYW0NCnRldHVlciBhZGlwaXNjaW5nIGVsaXQuIE51bGxhIHZpdGFlIGVsaXQgbGVybywgDQphIHBoYXJldHJhLiA8Yj5Mb3JlbSBpcHN1bTwvYj4gY3RldHVlciBhZGlwaXNjaW5nLiANCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LiI7fWk6NjthOjExOntzOjU6Im9yZGVyIjtzOjE6IjYiO3M6NToidGl0bGUiO3M6ODoiQW5ueSBEb2UiO3M6NDoicm9sZSI7czoxNjoiQ3VzdG9tZXIgU2VydmljZSI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvdGVhbU1lbWJlcjYucG5nIjtzOjQ6Imljb24iO3M6ODA6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3VwcG9ydFRlYW1JY29uLTEucG5nIjtzOjc6InR3aXR0ZXIiO3M6MzI6Imh0dHA6Ly90d2l0dGVyLmNvbS9wcmVtaXVtY29kaW5nIjtzOjg6ImZhY2Vib29rIjtzOjM2OiJodHRwOi8vd3d3LmZhY2Vib29rLmNvbS9HRmxhc2hEZXNpZ24iO3M6NToidmltZW8iO3M6MTY6Imh0dHA6Ly92aW1lby5jb20iO3M6NzoiZHJpYmJsZSI7czoyNzoiaHR0cDovL2RyaWJiYmxlLmNvbS9nbGppdmVjIjtzOjQ6Im1haWwiO3M6MjI6ImluZm9AcHJlbWl1bWNvZGluZy5jb20iO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjI3MToiPGI+TG9yZW0gaXBzdW08L2I+IGRvbG9yIHNpdCBhbWV0IGRhcyBjb25zZSANCm5pYmggZXVpc21vZG9zIHRpbmNpZHVudCB1dCBsYW9yZWUgY29uc2UNCmVzdCBhdC4gTnVsbGEgdml0YWUgPGI+ZWxpdCBsaWJlcm88L2I+LCBhIHBoYSBzaXQgYW0NCnRldHVlciBhZGlwaXNjaW5nIGVsaXQuIE51bGxhIHZpdGFlIGVsaXQgbGVybywgDQphIHBoYXJldHJhLiA8Yj5Mb3JlbSBpcHN1bTwvYj4gY3RldHVlciBhZGlwaXNjaW5nLiANCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LiI7fX1zOjExOiJwb3J0X251bWJlciI7czoyOiIxMiI7czoxODoic29ydGluZ3Bvc3RfbnVtYmVyIjtzOjI6IjEyIjtzOjExOiJzb2NpYWxpY29ucyI7YTo1OntpOjE7YTo0OntzOjU6Im9yZGVyIjtzOjE6IjEiO3M6NToidGl0bGUiO3M6ODoiRmFjZWJvb2siO3M6MzoidXJsIjtzOjgwOiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE1LzAyL2ZhY2Vib29rLXRvcC1pY29uLnBuZyI7czo0OiJsaW5rIjtzOjE5OiJodHRwOi8vZmFjZWJvb2suY29tIjt9aToyO2E6NDp7czo1OiJvcmRlciI7czoxOiIyIjtzOjU6InRpdGxlIjtzOjg6IkRyaWJiYmxlIjtzOjM6InVybCI7czo3OToiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNS8wMi90b3AtZHJpYmJsZS1pY29uLnBuZyI7czo0OiJsaW5rIjtzOjIwOiJodHRwOi8vZHJpYmJibGUuY29tLyI7fWk6MzthOjQ6e3M6NToib3JkZXIiO3M6MToiMyI7czo1OiJ0aXRsZSI7czo3OiJUd2l0dGVyIjtzOjM6InVybCI7czo3OToiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNS8wMi90b3AtdHdpdHRlci1pY29uLnBuZyI7czo0OiJsaW5rIjtzOjIwOiJodHRwczovL3R3aXR0ZXIuY29tLyI7fWk6NDthOjQ6e3M6NToib3JkZXIiO3M6MToiNCI7czo1OiJ0aXRsZSI7czoxNDoiRHJvcCB1cyBhIG5vdGUiO3M6MzoidXJsIjtzOjc2OiJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE1LzAyL3RvcC1tYWlsLWljb24ucG5nIjtzOjQ6ImxpbmsiO3M6Mjk6Im1haWx0bzppbmZvQHByZW1pdW1jb2RpbmcuY29tIjt9aTo1O2E6NDp7czo1OiJvcmRlciI7czoxOiI1IjtzOjU6InRpdGxlIjtzOjU6IlZpbWVvIjtzOjM6InVybCI7czo3NzoiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNS8wMi90b3AtdmltZW8taWNvbi5wbmciO3M6NDoibGluayI7czoxODoiaHR0cHM6Ly92aW1lby5jb20vIjt9fXM6MTI6ImNvbnRhY3RlbWFpbCI7czoxNzoiaW5mb0B5b3VybWFpbC5jb20iO3M6MTI6ImNvbnRhY3RlcnJvciI7czoyNToiRXJyb3Igd2hpbGUgc2VuZGluZyBtYWlsLiI7czoxNDoiY29udGFjdHN1Y2Nlc3MiO3M6NzoiU3VjY2VzcyI7czoxNDoiZXJyb3JwYWdldGl0bGUiO3M6MTA6Ik9PT1BTISA0MDQiO3M6MTc6ImVycm9ycGFnZXN1YnRpdGxlIjtzOjY1OiJTZWVtcyBsaWtlIHlvdSBzdHVtYmxlZCBhdCBzb21ldGhpbmcgdGhhdCBkb2VzblxcXCd0IHJlYWxseSBleGlzdCI7czo5OiJlcnJvcnBhZ2UiO3M6MTcxOiJTb3JyeSwgYnV0IHRoZSBwYWdlIHlvdSBhcmUgbG9va2luZyBmb3IgaGFzIG5vdCBiZWVuIGZvdW5kLjxici8+VHJ5IGNoZWNraW5nIHRoZSBVUkwgZm9yIGVycm9ycywgdGhlbiBoaXQgcmVmcmVzaC48L2JyPk9yIHlvdSBjYW4gc2ltcGx5IGNsaWNrIHRoZSBpY29uIGJlbG93IGFuZCBnbyBob21lOikiO3M6MTY6InNob3dzb2NpYWxmb290ZXIiO3M6MToiMSI7czo5OiJjb3B5cmlnaHQiO3M6Mjk6IsKpIDIwMTEgQWxsIHJpZ2h0cyByZXNlcnZlZC4gIjtzOjE2OiJ0cmFuc2xhdGlvbl9tZW51IjtzOjQ6Ik1lbnUiO3M6MTY6InRyYW5zbGF0aW9uX3Bvc3QiO3M6MTY6Ik91ciBsYXRlc3QgcG9zdHMiO3M6MjQ6InRyYW5zbGF0aW9uX2VudGVyX3NlYXJjaCI7czoxNToiRW50ZXIgc2VhcmNoLi4uIjtzOjE2OiJ0cmFuc2xhdGlvbl9wb3J0IjtzOjE2OiJSZWNlbnQgcG9ydGZvbGlvIjtzOjIzOiJ0cmFuc2xhdGlvbl9yZWxhdGVkcG9zdCI7czo3OiJSZWxhdGVkIjtzOjI3OiJ0cmFuc2xhdGlvbl9hZHZlcnRpc2VfdGl0bGUiO3M6MTY6Ik91ciBNYWpvciBCcmFuZHMiO3M6MjA6InRyYW5zbGF0aW9uX21vcmVsaW5rIjtzOjk6IlJlYWQgbW9yZSI7czoyNDoicG9ydF9wcm9qZWN0X2Rlc2NyaXB0aW9uIjtzOjIwOiJQcm9qZWN0IERlc2NyaXB0aW9uOiI7czoyMDoicG9ydF9wcm9qZWN0X2RldGFpbHMiO3M6MTY6IlByb2plY3QgZGV0YWlsczoiO3M6MTY6InBvcnRfcHJvamVjdF91cmwiO3M6MTI6IlByb2plY3QgVVJMOiI7czoyMToicG9ydF9wcm9qZWN0X2Rlc2lnbmVyIjtzOjE3OiJQcm9qZWN0IGRlc2lnbmVyOiI7czoxNzoicG9ydF9wcm9qZWN0X2RhdGUiO3M6Mjc6IlByb2plY3QgRGF0ZSBvZiBjb21wbGV0aW9uOiI7czoxOToicG9ydF9wcm9qZWN0X2NsaWVudCI7czoxNToiUHJvamVjdCBDbGllbnQ6IjtzOjE4OiJwb3J0X3Byb2plY3Rfc2hhcmUiO3M6MTc6IlNoYXJlIHRoZSBwcm9qZWN0IjtzOjIwOiJwb3J0X3Byb2plY3RfcmVsYXRlZCI7czoxNToiUmVsYXRlZCBwcm9qZWN0IjtzOjE1OiJ0cmFuc2xhdGlvbl9hbGwiO3M6ODoiU2hvdyBhbGwiO3M6MjQ6InRyYW5zbGF0aW9uX25leHRfcHJvamVjdCI7czoxNjoiTmV4dCBwcm9qZWN0IOKGkiI7czoyNzoidHJhbnNsYXRpb25fcHJldml1c19wcm9qZWN0IjtzOjE3OiLihpAgUHJldiBwcm9qZWN0ICI7czoxNDoidHJhbnNsYXRpb25fYnkiO3M6MzoiQnk6IjtzOjIyOiJ0cmFuc2xhdGlvbl9jYXRlZ29yaWVzIjtzOjExOiJDYXRlZ29yaWVzOiI7czoxNjoidHJhbnNsYXRpb25fdGFncyI7czo2OiJUYWdzOiAiO3M6MjY6InRyYW5zbGF0aW9uX3NoYXJlX2NhdGVnb3J5IjtzOjU6IlNoYXJlIjtzOjIxOiJ0cmFuc2xhdGlvbl9ibG9nX3BhZ2UiO3M6NTk6IldlbGNvbWUgdG8gPHNwYW4+b3VyIGJsb2c8L3NwYW4+LCB3ZSB3aWxsIGtlZXAgeW91IGluZm9ybWVkIjtzOjMyOiJ0cmFuc2xhdGlvbl9jb21tZW50X2xlYXZlX3JlcGxheSI7czo1OiJSZXBseSI7czozNToidHJhbnNsYXRpb25fY29tbWVudF9sZWF2ZV9yZXBsYXlfdG8iO3M6MTY6IkxlYXZlIGEgUmVwbHkgdG8iO3M6Mzk6InRyYW5zbGF0aW9uX2NvbW1lbnRfbGVhdmVfcmVwbGF5X2NhbmNsZSI7czoxMzoiQ2FuY2xlIFJlcGxheSI7czoyNDoidHJhbnNsYXRpb25fY29tbWVudF9uYW1lIjtzOjQ6Ik5hbWUiO3M6MjQ6InRyYW5zbGF0aW9uX2NvbW1lbnRfbWFpbCI7czo0OiJNYWlsIjtzOjI3OiJ0cmFuc2xhdGlvbl9jb21tZW50X3dlYnNpdGUiO3M6NzoiV2Vic2l0ZSI7czoyODoidHJhbnNsYXRpb25fY29tbWVudF9yZXF1aXJlZCI7czo4OiJyZXF1aXJlZCI7czoyNjoidHJhbnNsYXRpb25fY29tbWVudF9jbG9zZWQiO3M6MjA6IkNvbW1lbnRzIGFyZSBjbG9zZWQuIjtzOjMxOiJ0cmFuc2xhdGlvbl9jb21tZW50X25vX3Jlc3BvbmNlIjtzOjEwOiJObyBSZXBsaWVzIjtzOjMxOiJ0cmFuc2xhdGlvbl9jb21tZW50X29uZV9jb21tZW50IjtzOjk6Ik9uZSBSZXBseSI7czozMToidHJhbnNsYXRpb25fY29tbWVudF9tYXhfY29tbWVudCI7czo3OiJSZXBsaWVzIjtzOjI0OiJ0cmFuc2xhdGlvbl9jb250YWN0X25hbWUiO3M6NDoiTmFtZSI7czoyNToidHJhbnNsYXRpb25fY29udGFjdF9lbWFpbCI7czo1OiJFbWFpbCI7czoyNzoidHJhbnNsYXRpb25fY29udGFjdF9tZXNzYWdlIjtzOjc6Ik1lc3NhZ2UiO3M6MjQ6InRyYW5zbGF0aW9uX2NvbnRhY3Rfc2VuZCI7czoxMjoiU2VuZCBNZXNzYWdlIjtzOjI1OiJ0cmFuc2xhdGlvbl9jb250YWN0X2NsZWFyIjtzOjU6IkNsZWFyIjtzOjE4OiJyYWNlbnRfc3RhdHVzX3BvcnQiO3M6MDoiIjtzOjc6ImJvZHlfYmciO3M6MDoiIjtzOjk6ImhlYWRlcl9iZyI7czowOiIiO30=';
		$data = unserialize(base64_decode($data)); //100% safe - ignore theme check nag
		update_option('of_options_musica_pmc', $data);
		
	}
	//delete_option(OPTIONS);
	
}

// Build Options
$admin =  get_template_directory() . '/admin/';

require_once ($admin . 'theme-options.php');   // Options panel settings and custom settings
require_once ($admin . 'admin-interface.php');  // Admin Interfaces
require_once ($admin . 'admin-functions.php');  // Theme actions based on options settings
require_once ($admin . 'medialibrary-uploader.php'); // Media Library Uploader


$includes =  get_template_directory() . '/includes/';
$widget_includes =  get_template_directory() . '/includes/widgets/';

require_once ($includes  . 'scripts.php'); // Load JS 

// Other theme options
require_once ($includes . 'shortcodes.php');
	
require_once ($widget_includes . 'pop_widget.php'); 
require_once ($widget_includes . 'racent_widget.php'); 
require_once ($widget_includes . 'contact_widget.php'); 



// Load external file to add support for MultiPostThumbnails. Allows you to set more than one "feature image" per post.
require_once('includes/multi-post-thumbnails.php');

if (class_exists('MultiPostThumbnails')) {
    new MultiPostThumbnails(array(
        'label' => '2nd Feature Image',
        'id' => 'feature-image-2',
        'post_type' => 'portfolioentry'
        )
    );    
 
}

if (function_exists('icl_object_id')) { 
    function languages_list_footer(){
    $languages = icl_get_languages('skip_missing=0&orderby=code');
    if(!empty($languages)){
        echo '<div id="footer_language_list"><ul>';
        foreach($languages as $l){
            echo '<li>';
            if($l['country_flag_url']){
                if(!$l['active']) echo '<a href="'.$l['url'].'">';
                echo '<img src="'.$l['country_flag_url'].'" height="12" alt="'.$l['language_code'].'" width="18" />';
                if(!$l['active']) echo '</a>';
            }

            echo '</li>';
        }
        echo '</ul></div>';
    }
	}
	function current_language(){

		global $sitepress;

		$current_language = $sitepress->get_current_language();

		return $current_language;

	}
}    

	function showTopCart() {
		
		global $woocommerce, $data;

		?>
		<div class="cartHolder">
			<div class="top-nav">
				<div class="socialTop">
					<?php socialLinkTop() ?>
				</div>
				<?php	if (function_exists( 'is_woocommerce' ) ) : ?>
				<div class="cartWrapper">
					<a class="cart-bubble cart-contents">(<?php echo sprintf(_n('%d', '%d', $woocommerce->cart->cart_contents_count, 'woothemes'), $woocommerce->cart->cart_contents_count);?>)</a>
					<?php if($woocommerce->cart->get_cart_url() != ''){ $cart=$woocommerce->cart->get_cart_url();}
					else {$cart = home_url().'/cart/';};
					?>
					<a href="<?php echo $cart; ?>" class="cart-top"><?php echo $data['translation_cart'] ?></a>
				<div class="widget_shopping_cart_top">	
				<div class="cartTopDetails">
					<ul class="cart_list product_list_widget  <?php if(isset($args['list_class'])) echo $args['list_class']; ?>">

						<?php if ( sizeof( $woocommerce->cart->get_cart() ) > 0 ) : ?>

							<?php foreach ( $woocommerce->cart->get_cart() as $cart_item_key => $cart_item ) :

								$_product = $cart_item['data'];

								// Only display if allowed
								if ( ! apply_filters('woocommerce_widget_cart_item_visible', true, $cart_item, $cart_item_key ) || ! $_product->exists() || $cart_item['quantity'] == 0 )
									continue;

								// Get price
								$product_price = get_option( 'woocommerce_display_cart_prices_excluding_tax' ) == 'yes' || $woocommerce->customer->is_vat_exempt() ? $_product->get_price_excluding_tax() : $_product->get_price() ;
								
								$product_price = $product_price * $cart_item['quantity'];
								
								$product_price = apply_filters( 'woocommerce_cart_item_price_html', woocommerce_price( $product_price ), $cart_item, $cart_item_key );
								?>

								<li>
									<a href="<?php echo get_permalink( $cart_item['product_id'] ); ?>">


										<?php echo $cart_item['quantity'] ?> x <?php echo apply_filters('woocommerce_widget_cart_product_title', $_product->get_title(), $_product ); ?>

									</a>

									<?php //echo $woocommerce->cart->get_item_data( $cart_item ); ?>

									<span class="quantity"><?php printf( '%s',  $product_price ); ?></span>
								</li>

							<?php endforeach; ?>

						<?php else : ?>

							<li class="empty cart"><?php _e('No products in the cart.', 'woocommerce'); ?></li>

						<?php endif; ?>
					<?php if ( sizeof( $woocommerce->cart->get_cart() ) > 0 ) : ?>
							<p class="total top"><strong><?php _e('Subtotal', 'woocommerce'); ?>:</strong> <?php echo $woocommerce->cart->get_cart_subtotal(); ?></p>
						
						<?php do_action( 'woocommerce_widget_shopping_cart_before_buttons' ); ?>

						<p class="buttons">
							<a href="<?php echo $cart ; ?>" class="button"><?php _e('View Cart &rarr;', 'woocommerce'); ?></a>
							<a href="<?php echo $woocommerce->cart->get_checkout_url(); ?>" class="button checkout"><?php _e('Checkout &rarr;', 'woocommerce'); ?></a>
						</p>

				<?php endif; ?>
					</ul><!-- end product list -->
				</div>	
					
				</div>	
				</div>
					
				<?php endif; ?>	
				<?php if ( is_user_logged_in() ) {?> 				
				<ul>
				
				<?php 
				if ( has_nav_menu( 'top_menu' ) ) {
					wp_nav_menu( array('theme_location' => 'top_menu', 'container' => 'false', 'menu_class' => 'top-nav', 'echo' => true, 'items_wrap' => '%3$s' )); 
				}
				?>
				</ul>
				<?php } else {?>
				<ul>
				
				<?php 
					if ( has_nav_menu( 'top_menu' ) ) {
						wp_nav_menu( array('theme_location' => 'top_menu', 'container' => 'false', 'menu_class' => 'top-nav', 'echo' => true, 'items_wrap' => '%3$s' )); 
					}
					?>
					<li><a href="<?php echo home_url() ?>/my-account/"><?php echo $data['translation_login_register'] ?></a></li>
				</ul>				
				<?php } ?>
			</div>
		</div>
		<?php
	}


	if (function_exists( 'is_woocommerce' ) ) : 

	/*== WOO CUSTOMIZATION ==*/


	
	if(isset($data['product_cat_page']) && $data['product_cat_page'] != 'Select a number:'){

	add_filter('loop_shop_per_page', create_function('$cols', 'return '.$data['product_cat_page'].';'));
	
	}


    function get_image_pmc( $width, $height ,$id) {
        global $woocommerce;
 
        $image = '';
		if ( has_post_thumbnail() ){
			$image = wp_get_attachment_image_src(get_post_thumbnail_id($id), array($width,$height), false);
			$image = $image[0];
			}
		else
			$image = get_template_directory_uri() .'/images/placeholder-580.png'; 
 

		$image = '<img src="'. $image .'" >';
 
        return $image ;
     }	
	 
	add_filter('woocommerce_get_catalog_ordering_args', 'custom_woocommerce_get_catalog_ordering_args');
	
	function custom_woocommerce_get_catalog_ordering_args( $args ) {
		if (isset($_GET['orderby'])) {
			switch ($_GET['orderby']) :
				case 'date_asc' :
					$args['orderby'] = 'date';
					$args['order'] = 'asc';
					$args['meta_key'] = '';
				break;
				case 'price_desc' :
					$args['orderby'] = 'meta_value_num';
					$args['order'] = 'desc';
					$args['meta_key'] = '_price';
				break;
				case 'title_desc' :
					$args['orderby'] = 'title';
					$args['order'] = 'desc';
					$args['meta_key'] = '';
				break;
				case 'date_desc' :
					$args['orderby'] = 'date';
					$args['order'] = 'desc';
					$args['meta_key'] = '';
				break;
				case 'price' :
					$args['orderby'] = 'meta_value_num';
					$args['order'] = 'asc';
					$args['meta_key'] = '_price';
				break;
				case 'title_asc' :
					$args['orderby'] = 'title';
					$args['order'] = 'asc';
					$args['meta_key'] = '';
				break;	
				case 'select' :
					$args['orderby'] = '';
					$args['order'] = '';
					$args['meta_key'] = '';
				break;					
			endswitch;
		}
		return $args;
	}
	
	
	

	
	


	
	// Ensure cart contents update when products are added to the cart via AJAX (place the following in functions.php)
	add_filter('add_to_cart_fragments', 'woocommerce_header_add_to_cart_fragment');

	function woocommerce_header_add_to_cart_fragment( $fragments ) {
		global $woocommerce;
		ob_start();
		?>
		<a class="cart-bubble cart-contents">(<?php echo sprintf(_n('%d', '%d', $woocommerce->cart->cart_contents_count, 'woothemes'), $woocommerce->cart->cart_contents_count);?>)</a>
		<?php

		$fragments['a.cart-contents'] = ob_get_clean();

		return $fragments;
	}
	
	
	
	add_action('woocommerce_before_main_content', create_function('', 'echo "";'), 10);
	add_action('woocommerce_after_main_content', create_function('', 'echo "";'), 10);

	// remove ordering
	
	remove_action( 'woocommerce_pagination', 'woocommerce_catalog_ordering', 20 );

	
	function pmc_woocommerce_image_dimensions() {
		global $pagenow;
	 
		if ( ! isset( $_GET['activated'] ) || $pagenow != 'themes.php' ) {
			return;
		}

		$catalog = array(
			'width' 	=> '260',	// px
			'height'	=> '220',	// px
			'crop'		=> 1 		// true
		);

		$single = array(
			'width' 	=> '700',	// px
			'height'	=> '600',	// px
			'crop'		=> 1 		// true
		);

		$thumbnail = array(
			'width' 	=> '110',	// px
			'height'	=> '90',	// px
			'crop'		=> 1 		// false
		);

		// Image sizes
		update_option( 'shop_catalog_image_size', $catalog ); 		// Product category thumbs
		update_option( 'shop_single_image_size', $single ); 		// Single product image
		update_option( 'shop_thumbnail_image_size', $thumbnail ); 	// Image gallery thumbs
	}

	add_action( 'after_switch_theme', 'pmc_woocommerce_image_dimensions', 1 );

	

	/**
	 * WooCommerce Extra Feature
	 * --------------------------
	 */ 
	function woo_related_products_limit() {
	  global $product;
		
		$args['posts_per_page'] = 3;
		return $args;
	}
	
	remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_upsell_display', 15 );
	add_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_upsells', 15 );
	if ( ! function_exists( 'woocommerce_output_upsells' ) ) {
		function woocommerce_output_upsells() {
			woocommerce_upsell_display( 3,4 ); // Display 3 products in rows of 3
		}
	}	

	
	function woocommerce_output_related_products() {
	woocommerce_related_products(3,1); // Display 3 products in rows of 3
	}
		
		

	
endif;	



function fl_shortcode_button() {
	if ( ! current_user_can('edit_posts') && ! current_user_can('edit_pages') )
		return;

	// Add only in Rich Editor mode
	if ( get_user_option('rich_editing') == 'true') {
		add_filter("mce_external_plugins", "fl_add_shortcode_tinymce_plugin");
		add_filter('mce_buttons', 'fl_register_shortcode_button');
	}
}

 
 if ( ! isset( $content_width ) ) $content_width = 960;
/**
 * Register the TinyMCE Shortcode Button
 */
function fl_register_shortcode_button($buttons) {
	array_push($buttons, "|", "flshortcodes");
	return $buttons;
}

/**
 * Load the TinyMCE plugin: shortcode_plugin.js
 */
function fl_add_shortcode_tinymce_plugin($plugin_array) {
   $plugin_array['flshortcodes'] = get_template_directory_uri() . '/js/shortcode_plugin.js';
   return $plugin_array;
}
 


function shortcontent($start, $end, $new, $source, $lenght){
$text = strip_tags(preg_replace('/<h(.*)>(.*)<\/h(.*)>.*/iU', '', $source), '<b><strong>');
$text = preg_replace('#\[video\](.*)\[\/video\]#si', '', $text);
$text = preg_replace('#\[pmc_link\](.*)\[\/pmc_link\]#si', '', $text);
$text = preg_replace('/\[[^\]]*\]/', $new, $text); 
return substr(preg_replace('/\s[\s]+/','',$text),0,$lenght);

}

function fl_refresh_mce($ver) {
  $ver += 3;
  return $ver;
}

/* custom breadcrumb */
function the_breadcrumb() {
	if (!is_home()) {
		echo '<a href="';
		echo home_url();
		echo '">';
		bloginfo('name');
		echo "</a> &#187; ";
		if (is_single()) {
			if (is_single()) {
				the_title();
			}
		} elseif (is_page()) {
			echo the_title();
		}
		elseif(get_query_var('portfoliocategory')){
			$cat = get_query_var('portfoliocategory');
			$cat = str_replace('-',' ',$cat);
			echo $cat;
		}	
		else if(get_query_var('tag')){
			$tag = get_query_var('tag');
			$tag = str_replace('-',' ',$tag);
			echo $tag;
		}
		else if(get_query_var('s')){
			the_search_query();				
		} 
		else if(get_query_var('cat')){
			$cat = get_query_var('cat');
			$cat = get_category($cat);
			echo $cat->name;
		}
		else if(get_query_var('m')){
			echo __('Archive','wp-musica');
		}		
		else{
			echo 'Home';
		}
	}
}


function social($url) {
	$social = '';
	global $data; 
	$icons = $data['socialicons'];
	foreach ($icons as $icon){
		$social .= '<a target="_blank" class="'.$icon['class'].'" href="'.$icon['link'].'" title="'.$icon['title'].'"><img src = "'.$icon['url'].'" alt="'.$icon['title'].'"></a>';	
	}

	echo $social;
}




function footer(){
	function pmc_recent_footer_excerpt_length( $length ) {
		return 40;
	}
	
	function pmc_recent_footer_title($title) { return  substr($title, 0, 40). '';}
		
	add_filter( 'excerpt_length', 'pmc_recent_footer_excerpt_length', 999 );
	add_filter('the_title', 'pmc_recent_footer_title') ;
}

function shortTitle($lenght)
{
	$title = the_title('','',FALSE); 
	echo substr($title, 0, $lenght);
}
function custom_excerpt_length( $length ) {
	return 30;
}
add_filter( 'excerpt_length', 'custom_excerpt_length', 999 );
function new_excerpt_more($more) {
	return '';
}
add_filter('excerpt_more', 'new_excerpt_more');



function socialLinkProduct() {
	$social = '';
	$social ='<div class="addthis_toolbox"><div class="custom_images">';
	global $data; 
	$social .= '<a class="addthis_button_facebook" title="'.translation('translation_facebook', 'Facebook').'"><img src="'. get_template_directory_uri() .'/images/icon-facebook-product-single.png" width="16" height="16"  alt="'.translation('translation_facebook', 'Facebook').'" /></a>';            
	$social .= '<a class="addthis_button_twitter" title="'.translation('translation_twitter', 'Twitter').'"><img src="'. get_template_directory_uri() .'/images/icon-twitter-product-single.png" width="16" height="16"  alt="'.translation('translation_twitter', 'Twitter').'" /></a>';  
	$social .='<a class="addthis_button_more"><img src="'. get_template_directory_uri() .'/images/icon-more-product-single.png" width="16" height="16"  alt="More..." /></a></div><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f3049381724ac5b"></script>';	
	if(isset($data['email']))
	$social .= '<a class="emaillink" href="mailto:'.$data['email'].'" title="'.translation('translation_email', 'Send us Email').'"></a></div>'; 
	echo $social;
}

function socialLinkTop() {
	$social = '';
	global $data; 
	$icons = $data['socialicons'];
	foreach ($icons as $icon){
		$social .= '<a target="_blank"  href="'.$icon['link'].'" title="'.$icon['title'].'"><img src = "'.$icon['url'].'" alt="'.$icon['title'].'"></a>';	
	}

	echo $social;
}

function socialLinkTeam($facebook,$twitter,$vimeo,$dribble,$email) {
	$social = '';
	global $data; 
	if($facebook != '')
	$social .= '<a target="_blank" class="facebooklink" href="'.$facebook.'" title="'.translation('translation_facebook', 'Facebook').'"></a>';            
	if($twitter != '')
	$social .= '<a target="_blank" class="twitterlink" href="'.$twitter.'" title="'.translation('translation_twitter', 'Twitter').'"></a>';  
	if($vimeo != '') 
	$social .= '<a target="_blank" class="vimeo" href="'.$vimeo.'" title="'.translation('translation_vimeo', 'Vimeo').'"></a>';  
	if($dribble != '')
	$social .= '<a target="_blank" class="dribble" href="'.$dribble.'" title="'.translation('translation_dribble', 'Dribble').'"></a>';  
	if($email != '') 
	$social .= '<a target="_blank" class="emaillink" href="mailto:'.$email.'" title="'.translation('translation_email', 'Send us Email').'"></a>';  	
	echo $social;
}


function socialLinkCat($link,$title,$email) {
	global $data,$sitepress;; 
	$social = '';
	$social .='<a class="addthis_button" addthis:url="'.$link.'" addthis:title="'.$title.'" ><img src="'. get_template_directory_uri() .'/images/socialIconShareMore.png" width="64" height="64"  alt="More..." />';
	$social .= translation('translation_share_category', 'Share'); 
	$social .='</a><script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-507800a118eab6fa"></script>';	

	echo $social; }



function socialLinkSingle() {
	$social = '';
	$social ='<div class="addthis_toolbox"><div class="custom_images">';
	global $data; 
	$social .= '<a class="addthis_button_facebook" title="'.translation('translation_facebook', 'Facebook').'"><img src="'. get_template_directory_uri() .'/images/facebookPortfolioIcon.png" width="64" height="64"  alt="'.translation('translation_facebook', 'Facebook').'" /></a>';            
	$social .= '<a class="addthis_button_twitter" title="'.translation('translation_twitter', 'Twitter').'"><img src="'. get_template_directory_uri() .'/images/twitterPortfolioIcon.png" width="64" height="64"  alt="'.translation('translation_twitter', 'Twitter').'" /></a>';  
	$social .='<a class="addthis_button_more"><img src="'. get_template_directory_uri() .'/images/addPortfolioIcon.png" width="64" height="64"  alt="More..." /></a></div><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f3049381724ac5b"></script>';	
	$social .= '<a class="emaillink" href="mailto:'.$data['email'].'" title="'.translation('translation_email', 'Send us Email').'"><img src="'. get_template_directory_uri() .'/images/emailPortfolioIcon.png" width="24" height="24"  alt="More..." /></a></div>'; 
	echo $social;
}

function translation($theme_name, $translation_name){
	global $data, $sitepress;
	if (!function_exists('icl_object_id') or (ICL_LANGUAGE_CODE == $sitepress->get_default_language()) ) { 
		if(isset($data[$theme_name]))
			$string = stripText($data[$theme_name]); 
		else
			$string = '';
		} 
	else {  
		$string = __($translation_name,'wp-musica'); 				
	} 
	return $string;

}

function get_category_id($cat_name){
	$term = get_term_by('name', $cat_name, 'category');
	return $term->term_id;
}
/**
 * Init process for button control
 */
add_filter( 'tiny_mce_version', 'fl_refresh_mce');
add_action( 'init', 'fl_shortcode_button' );


add_filter('the_content', 'addlightboxrel_replace');

function addlightboxrel_replace ($content)
{	global $post;
	$pattern = "/<a(.*?)href=('|\")(.*?).(bmp|gif|jpeg|jpg|png)('|\")(.*?)>/i";
  	$replacement = '<a$1href=$2$3.$4$5 rel="lightbox[%LIGHTID%]"$6>';
    $content = preg_replace($pattern, $replacement, $content);
	if(isset($post->ID))
		$content = str_replace("%LIGHTID%", $post->ID, $content);
    return $content;
}


function filter_content_video( $content ){
	$content = explode('[video]', $content );
	$content = explode('[/video]',$content[1] );					
	$content = $content[0];
	return $content;
}

function filter_content( $content ){
	$content = explode('[video]', $content );
	$contentpost = $content[0] . '';
	$content = explode('[/video]',$content[1] );	
	$contentpost .= $content[1]; 
	return $contentpost;
}

function filter_link( $content ){
	$content = explode('[pmc_link]', $content );
	$content = explode('[/pmc_link]',$content[1] );	
	$content = $content[0];
	return $content;
}

function filter_content_link( $content ){
	$content = explode('[pmc_link]', $content );
	$contentcat = $content[0];
	$content = explode('[/pmc_link]',$content[1] );	
	$contentcat .= $content[1];	
	return $contentcat;
}

function filter_content_gallery( $content ){
	$content = explode('[gallery]', $content );	
	$contentgal = $content[0];	
	return $contentgal;
}


/**
 * Add "first" and "last" CSS classes to dynamic sidebar widgets. Also adds numeric index class for each widget (widget-1, widget-2, etc.)
 */
function widget_first_last_classes($params) {

	global $my_widget_num; // Global a counter array
	$this_id = $params[0]['id']; // Get the id for the current sidebar we're processing
	$arr_registered_widgets = wp_get_sidebars_widgets(); // Get an array of ALL registered widgets	

	if(!$my_widget_num) {// If the counter array doesn't exist, create it
		$my_widget_num = array();
	}

	if(!isset($arr_registered_widgets[$this_id]) || !is_array($arr_registered_widgets[$this_id])) { // Check if the current sidebar has no widgets
		return $params; // No widgets in this sidebar... bail early.
	}

	if(isset($my_widget_num[$this_id])) { // See if the counter array has an entry for this sidebar
		$my_widget_num[$this_id] ++;
	} else { // If not, create it starting with 1
		$my_widget_num[$this_id] = 1;
	}

	$class = 'class="widget-' . $my_widget_num[$this_id] . ' '; // Add a widget number class for additional styling options

	if($my_widget_num[$this_id] == 1) { // If this is the first widget
		$class .= 'widget-first ';
	} elseif($my_widget_num[$this_id] == count($arr_registered_widgets[$this_id])) { // If this is the last widget
		$class .= 'widget-last ';
	}

	$params[0]['before_widget'] = str_replace('class="', $class, $params[0]['before_widget']); // Insert our new classes into "before widget"

	return $params;

}
add_filter('dynamic_sidebar_params','widget_first_last_classes');

function stripText($string) 
{ 
    return str_replace("\\",'',$string);
} 



/*portfolio loop*/

function portfolio($height, $width, $item, $post = 'port' ,$number = 0,$cat = ''){
	global $data; 
	$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
	$categport = '';


	if($post == 'post'){
		$postT = 'post';
		$showposts = $data['sortingpost_number'];
		$postC = 'category';	
		$categport="";		
		}
	else{
		$postT = 'portfolioentry';
		$postC = 'portfoliocategory';
		$showposts = $data['port_number'];
		if($cat != '')
			$categport='&portfoliocategory='.$cat;
		}
		
	if($number != 0)
		$showposts = $number;
		
	$postPage = '&posts_per_page='.$showposts;		
		
	if($item == 3){
		$titleChar = 999;
	}
	else if($item == 2){
		$titleChar = 25;
	}	
	else {
		$titleChar = 25;
	}


	if($categport != "")
		$pmc = new WP_Query(array('orderby=date', 'post_type' =>  $postT, 'paged' => $paged, 'post_status' => 'publish', 'ignore_sticky_posts' => 1, 'posts_per_page' => $showposts ,'portfoliocategory' => $cat )); 
	else
		$pmc = new WP_Query(array('orderby=date', 'post_type' =>  $postT, 'post_status' => 'publish', 'ignore_sticky_posts' => 1, 'posts_per_page' => $showposts , 'paged' => $paged,'suppress_filters' => false)); 
		

	$limit_text = 100;
	$currentindex = '';
	$counter = 0;
	$portfolio = '';
	$count = 0;
	while ( $pmc->have_posts() ) : $pmc->the_post();
		$do_not_duplicate = get_the_ID(); 
		$full_image = wp_get_attachment_image_src(get_post_thumbnail_id(), 'full', false);
		$entrycategory = get_the_term_list( get_the_ID(), $postC, '', ';', '' );
		$catstring = $entrycategory;
		$catstring = strip_tags($catstring);
		$catidlist = explode(";", $catstring);
		for($i = 0; $i < sizeof($catidlist); ++$i){
			$catidlist[$i].=$currentindex;
			$find =     array("&", "/", " ","amp;","&#38;","@");
			$replace  = array("", "", "", "","","");		
			$catlist .= str_replace($find,$replace,$catidlist[$i]). ' ';
		}


		$counter++;
		$category = get_the_term_list( get_the_ID(), $postC, '', ', ', '' );	
		if ( has_post_format( 'link' , get_the_ID())) 
			$linkPost = filter_link(get_the_content());
		else
			if (function_exists('icl_object_id')) 
				$linkPost = get_permalink(icl_object_id(get_the_ID(), 'portfolioentry', true, true));
			else 
				$linkPost = get_permalink();
				
		
		if($item != 2){

		$portfolio .= '<div class="item'.$item.' '.$catlist .'" data-category="'. $catlist.'">';
			if($item != 3) {
				$full_image = wp_get_attachment_image_src(get_post_thumbnail_id(), 'port4', false);
				$portfolio .= '
				<div class="overdefult">
					<a href="'. $linkPost .'">	
						<div class="portDate">'.  get_the_date() .'</div>
						<div class="portIcon"></div>
						<div class="portCategory">'. $category .'</div>
					</a>
				</div>
			<div class="image">
				<div class="loading"></div>
				<img src="'. $full_image[0] .'" alt="'. the_title('','',FALSE) .'">
			</div>';}
			if($item == 3) {
			$full_image = wp_get_attachment_image_src(get_post_thumbnail_id(), 'port3', false);
			$portfolio .= '
				<div class="recentimage">
					<div class="overdefult">
							<a class="overdefultlink" href="'. $linkPost .'">
								<div class="portDate">'. get_the_date() .'</div>
								<div class="portIcon"></div>
								<div class="portCategory">'. $category .'</div>
							</a>
					</div>
					<div class="image">
						<div class="loading"></div>
						<img src="'. $full_image[0] .'" alt="'. the_title('','',FALSE) .'">
					</div>
				</div>';
			}
			
		
			if($item != 3) 
				$portfolio .= '<h4><a href="'. $linkPost .'">'. substr(the_title('','',FALSE),0,$titleChar)  .'</a></h4>';
			if($item == 3) {
				$portfolio .= '<div class="recentdescription">
					<h3><a class="overdefultlink" href="'. $linkPost .'">'.  substr(the_title('','',FALSE),0,$titleChar)  .'</a></h3>
					
					<div class="descriptionHomePort">
						<div class="borderLine"><div class="borderLineLeft"></div><div class="borderLineRight"></div></div>
						<div>'. shortcontent("[", "]", "", get_the_content() ,145) .'...'.closeTagsReturn(shortcontent("[", "]", "", get_the_content() ,145)).'</div>
					</div>
				</div>';
			}
			

		$portfolio .= '</div>';
		
		} else {
		$category = get_the_term_list( get_the_ID(), $postC, '', '', '' );	
		$categoryHover = get_the_term_list( get_the_ID(), $postC, '', ', ', '' );			
		if($count != 2){
			$portfolio .= '<div class="one_half item2 '.$catlist .'" data-category="'. $catlist.'" >';
		}
		else{
			$portfolio .= '<div class="one_half last item2 '.$catlist .'" data-category="'. $catlist.'" >';
			$count = 0;
		}
			$full_image = wp_get_attachment_image_src(get_post_thumbnail_id(), 'port2', false);
			$portfolio .= '	<div class="recentimage">
					<div class="overdefult">
						<a href="'. $linkPost .'">	
							<div class="portDate">'. get_the_date() .'</div>
							<div class="portIcon"></div>
							<div class="portCategory">'. $categoryHover  .'</div>
						</a>
					</div>
				
					<div class="image">
						<div class="loading"></div>
						<img src="'. $full_image[0] .'" alt="'. the_title('','',FALSE) .'">
					</div>
				</div>
				<div class="recentdescription">
					<h3><a class="overdefultlink" href="'.$linkPost.'">'. substr(the_title('','',FALSE),0,99999) .'</a></h3>
					<h3 class="category">'. $category .'</h3>	
					<div class="description">'. shortcontent("[", "]", "", get_the_content() ,145) .'...'.closeTagsReturn(shortcontent("[", "]", "", get_the_content() ,145)).'</div>
				</div>
			</div>';

		$count++;
		
		}

		

	endwhile; 	

	echo $portfolio;
}

add_action('init', 'create_portfolio');

function create_portfolio() {
	$portfolio_args = array(
		'label' => 'Portfolio',
		'singular_label' => 'Portfolio',
		'public' => true,
		'show_ui' => true,
		'capability_type' => 'post',
		'hierarchical' => false,
		'rewrite' => true,
		'supports' => array('title', 'editor', 'thumbnail', 'author', 'comments', 'excerpt')
	);
	register_post_type('portfolioentry',$portfolio_args);
}
add_action("admin_init", "add_portfolio");
add_action('save_post', 'update_portfolio_data');

function add_portfolio(){
	add_meta_box("portfolio_details", "Portfolio Entry Options", "portfolio_options", "portfolioentry", "normal", "high");
}

function update_portfolio_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["author"]) ) {
			update_post_meta($post->ID, "author", $_POST["author"]);
		}
		if( isset($_POST["date"]) ) {
			update_post_meta($post->ID, "date", $_POST["date"]);
		}
		if( isset($_POST["detail_active"]) ) {
			update_post_meta($post->ID, "detail_active", $_POST["detail_active"]);
		}else{
			update_post_meta($post->ID, "detail_active", 0);
		}
		if( isset($_POST["website_url"]) ) {
			update_post_meta($post->ID, "website_url", $_POST["website_url"]);
		}
		if( isset($_POST["status"]) ) {
			update_post_meta($post->ID, "status", $_POST["status"]);
		}		
		if( isset($_POST["customer"]) ) {
			update_post_meta($post->ID, "customer", $_POST["customer"]);
		}			

	}
}

function portfolio_options(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["author"][0])){
		$author = $data["author"][0];
	}else{
		$author = "";
	}
	if (isset($data["date"][0])){
		$date = $data["date"][0];
	}else{
		$date = "";
	}
	if (isset($data["status"][0])){
		$status = $data["status"][0];
	}else{
		$status = "";
	}	
	if (isset($data["detail_active"][0])){
		$detail_active = $data["detail_active"][0];
	}else{
		$detail_active = 0;
		$data["detail_active"][0] = 0;
	}
	if (isset($data["website_url"][0])){
		$website_url = $data["website_url"][0];
	}else{
		$website_url = "";
	}
	
	if (isset($data["customer"][0])){
		$customer = $data["customer"][0];
	}else{
		$customer = "";
	}	 ?>
    <div id="portfolio-options">
        <table cellpadding="15" cellspacing="15">
        	<tr>
                <td colspan="2"><strong>Portfolio Overview Options:</strong></td>
            </tr>
            <tr>
                <td><label>Link to Detail Page: <i style="color: #999999;">(Do you want a project detail page?)</i></label></td><td><input type="checkbox" name="detail_active" value="1" <?php if( isset($detail_active)){ checked( '1', $data["detail_active"][0] ); } ?> /></td>	
            </tr>
            <tr>
            	<td><label>Project Link: <i style="color: #999999;">(The URL of your project)</i></label></td><td><input name="website_url" style="width:100%" value="<?php echo $website_url; ?>" /></td>
            </tr>
            <tr>
            	<td><label>Project Author: <i style="color: #999999;">(The URL of your project)</i></label></td><td><input name="author" style="width:100%" value="<?php echo $author; ?>" /></td>
            </tr>
            <tr>
            	<td><label>Project date: <i style="color: #999999;">(Date of project)</i></label></td><td><input name="date" style="width:100%" value="<?php echo $date; ?>" /></td>
            </tr>	
            <tr>
            	<td><label>Customer: <i style="color: #999999;">(Customer of project)</i></label></td><td><input name="customer" style="width:100%" value="<?php echo $customer; ?>" /></td>
            </tr>				
            <tr>
            	<td><label>Project status: <i style="color: #999999;">(Status of project)</i></label></td><td><input name="status" style="width:100%" value="<?php echo $status; ?>" /></td>
            </tr>				
        </table>
    </div>
      
<?php
}	
	
function add_portfolio_category(){
	add_meta_box("portfolio_categories", "Portfolio categories(only for portfolio templates)", "portfolio_category_options", "page", "normal", "high");
}	

add_action('save_post', 'update_portfolio_category_data');
add_action("admin_init", "add_portfolio_category");

function portfolio_category_options(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["port_category"][0])){
		$port_category = $data["port_category"][0];
	}else{
		$port_category = "";
	}
	if (isset($data["rev_slider"][0])){
		$rev_slider = $data["rev_slider"][0];
	}else{
		$rev_slider = "";
	}	

?>
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">
        	<tr>
                <td colspan="2"><strong>Portfolio category(only for portfolio templates):</strong></td>
            </tr>
            <tr>
            	<td><label>Category: <i style="color: #999999;">(select category)</i></label></td><td>
				<?php wp_dropdown_categories('show_option_all=Show all&hierarchical=2&name=port_category&taxonomy=portfoliocategory&selected='.$port_category.''); ?>
				</td>
            </tr>
			
        </table>
    </div>
	
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">
        	<tr>
                <td colspan="2"><strong>revolution slider(only for Revolution slider templates):</strong></td>
            </tr>
            <tr>
            	<td><label>Revolution slider: <i style="color: #999999;">(slider alias)</i></label></td><td><input name="rev_slider" style="width:100%" value="<?php echo $rev_slider; ?>" /></td>
            </tr>
			
        </table>
    </div>	
      
<?php
}
function update_portfolio_category_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["port_category"]) ) {
			update_post_meta($post->ID, "port_category", $_POST["port_category"]);
		}		
		if( isset($_POST["rev_slider"]) ) {
			update_post_meta($post->ID, "rev_slider", $_POST["rev_slider"]);
		}			

	}
}


register_taxonomy("portfoliocategory", array("portfolioentry"), array("hierarchical" => true, "label" => "Portfolio Categories", "singular_label" => "Portfolio Category", "rewrite" => true));

function getcatslug($catID){
		$cat_obj = get_term($catID, 'portfoliocategory');
		$cat_slug = '';
		$cat_slug = $cat_obj->slug;
		return $cat_slug;
	}

function add_slider_category(){
	add_meta_box("slider_categories", "Post type --- Supported post types: standard, video, link, audio amd gallery. ", "slider_category_options_post", "post", "normal", "high");
	
}	


add_action('save_post', 'update_slider_category_data');
add_action("admin_init", "add_slider_category");

function slider_category_options(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["slider_category"][0])){
		$slider_category = $data["slider_category"][0];
	}else{
		$slider_category = "";
	}

?>
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">		
		
        	<tr>
                <td colspan="2"><strong>Select slider:</strong></td>
            </tr>
			
            <tr>
            	<td><label>Slider: <i style="color: #999999;">(select slider for this page/post)</i></label></td><td>
				<?php wp_dropdown_categories('show_option_all=None&hierarchical=2&name=slider_category&taxonomy=sliderocategory&selected='.$slider_category.''); ?>
				</td>
            </tr>
        </table>
    </div>

      
<?php
}

function slider_category_options_post(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["slider_category"][0])){
		$slider_category = $data["slider_category"][0];
	}else{
		$slider_category = "";
	}
	if (isset($data["video_post_url"][0])){
		$video_post_url = $data["video_post_url"][0];
	}else{
		$video_post_url = "";
	}	
	if (isset($data["video_active_post"][0])){
		$video_active_post = $data["video_active_post"][0];
	}else{
		$video_active_post = 0;
		$data["video_active_post"][0] = 0;
	}	
	
	if (isset($data["link_post_url"][0])){
		$link_post_url = $data["link_post_url"][0];
	}else{
		$link_post_url = "";
	}	
	
	if (isset($data["audio_post_url"][0])){
		$audio_post_url = $data["audio_post_url"][0];
	}else{
		$audio_post_url = "";
	}	

	if (isset($data["audio_post_title"][0])){
		$audio_post_title = $data["audio_post_title"][0];
	}else{
		$audio_post_title = "";
	}	
	
	if (isset($data["selectv"][0])){
		$selectv = $data["selectv"][0];
	}else{
		$selectv = "";
	}	
	
	

?>
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">
		
         <tr class="videoonly">
            	<td><label>Video URL(*required) - add only if you select video post: <i style="color: #999999;">
				<br>Link should look for Youtube: http://www.youtube.com/watch?v=WhBoR_tgXCI - So ID is WhBoR_tgXCI
				<br>Link should look for Vimeo: http://vimeo.com/29017795 so ID is 29017795 <br></i></label><br><input name="video_post_url" style="width:500px" value="<?php echo $video_post_url; ?>" />
				</td>
				<td class="select_video" style="text-align:left;">
					<label>Select video: <i style="color: #999999;"><br><br>
					<select name="selectv">
					<?php if ($selectv == 'vimeo') {?>
					  <option value="vimeo" selected>Vimeo</option>
					 <?php } else {?>
					  <option value="vimeo">Vimeo</option>						
					 <?php }?>	
					<?php if ($selectv == 'youtube') {?>				 
					  <option value="youtube" selected>YouTube</option>
					 <?php } else {?>
					  <option value="youtube">YouTube</option>						
					 <?php }?>					  
					</select>
				</td>	
            </tr>			
            <tr class="linkonly">
            	<td><label>Link URL - add only if you select link post: <i style="color: #999999;"></i></label><br></td><td><input name="link_post_url" style="width:500px" value="<?php echo $link_post_url; ?>" /></td>
            </tr>				

            <tr class="audioonly">
            	<td><label>Audio URL - add only if you select audio post: <i style="color: #999999;"></i></label><br></td><td><input name="audio_post_url" style="width:500px" value="<?php echo $audio_post_url; ?>" /></td>
            </tr>
            <tr class="audioonly">
            	<td><label>Audio title - add only if you select audio post: <i style="color: #999999;"></i></label><br></td><td><input name="audio_post_title" style="width:500px" value="<?php echo $audio_post_title; ?>" /></td>
            </tr>					
			
        </table>

    </div>
	
      
<?php


	
}


function update_slider_category_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["slider_category"]) ) {
			update_post_meta($post->ID, "slider_category", $_POST["slider_category"]);
		}	
		if( isset($_POST["video_post_url"]) ) {
			update_post_meta($post->ID, "video_post_url", $_POST["video_post_url"]);
		}	
		if( isset($_POST["video_active_post"]) ) {
			update_post_meta($post->ID, "video_active_post", $_POST["video_active_post"]);
		}else{
			update_post_meta($post->ID, "video_active_post", 0);
		}		
		if( isset($_POST["link_post_url"]) ) {
			update_post_meta($post->ID, "link_post_url", $_POST["link_post_url"]);
		}	
		if( isset($_POST["audio_post_url"]) ) {
			update_post_meta($post->ID, "audio_post_url", $_POST["audio_post_url"]);
		}		
		if( isset($_POST["audio_post_title"]) ) {
			update_post_meta($post->ID, "audio_post_title", $_POST["audio_post_title"]);
		}					
		if( isset($_POST["selectv"]) ) {
			update_post_meta($post->ID, "selectv", $_POST["selectv"]);
		}			
	}
	
	
	
}

if (function_exists( 'is_woocommerce' ) ) {

function add_product_meta(){
	add_meta_box("product_meta", "Custom product options", "meta_product_options_post", "product", "normal", "high");
}	

add_action("admin_init", "add_product_meta");
add_action('save_post', 'update_product_meta_data');

function update_product_meta_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["meta_post_hover"]) ) {
			update_post_meta($post->ID, "meta_post_hover", $_POST["meta_post_hover"]);
		}		
		if( isset($_POST["video_post_url"]) ) {
			update_post_meta($post->ID, "video_post_url", $_POST["video_post_url"]);
		}	
	
		if( isset($_POST["selectv"]) ) {
			update_post_meta($post->ID, "selectv", $_POST["selectv"]);
		}	
		if( isset($_POST["video_active"]) ) {
			update_post_meta($post->ID, "video_active", $_POST["video_active"]);
		}else{
			update_post_meta($post->ID, "video_active", 0);
		}	
		if( isset($_POST["meta_hover_short"]) ) {
			update_post_meta($post->ID, "meta_hover_short", $_POST["meta_hover_short"]);
		}else{
			update_post_meta($post->ID, "meta_hover_short", 0);
		}	
		
		if( isset($_POST["audio_product_url"]) ) {
			update_post_meta($post->ID, "audio_product_url", $_POST["audio_product_url"]);
		}else{
			update_post_meta($post->ID, "audio_product_url", 0);
		}
		
		if( isset($_POST["audio_product_title"]) ) {
			update_post_meta($post->ID, "audio_product_title", $_POST["audio_product_title"]);
		}else{
			update_post_meta($post->ID, "audio_product_title", 0);
		}
		
		if( isset($_POST["audio_show"]) ) {
			update_post_meta($post->ID, "audio_show", $_POST["audio_show"]);
		}else{
			update_post_meta($post->ID, "audio_show", 0);
		}
		
	}
	
	
	
}

function meta_product_options_post(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["video_post_url"][0])){
		$video_post_url = $data["video_post_url"][0];
	}else{
		$video_post_url = "";
	}	
	if (isset($data["meta_post_hover"][0])){
		$meta_post_hover = $data["meta_post_hover"][0];
	}else{
		$meta_post_hover = "";
	}		
	
	if (isset($data["audio_product_url"][0])){
		$audio_product_url = $data["audio_product_url"][0];
	}else{
		$audio_product_url = "";
	}	
	
	if (isset($data["audio_product_title"][0])){
		$audio_product_title = $data["audio_product_title"][0];
	}else{
		$audio_product_title = "";
	}	

	if (isset($data["audio_show"][0])){
		$audio_show = $data["audio_show"][0];
	}else{
		$audio_show = "";
	}		
		
	
	if (isset($data["selectv"][0])){
		$selectv = $data["selectv"][0];
	}else{
		$selectv = "";
	}	
	if (isset($data["video_active"][0])){
		$video_active = $data["video_active"][0];
	}else{
		$video_active = 0;
		$data["video_active"][0] = 0;
	}
	if (isset($data["meta_hover_short"][0])){
		$meta_hover_short = $data["meta_hover_short"][0];
	}else{
		$meta_hover_short = 0;
		$data["meta_hover_short"][0] = 0;
	}	
	
	

?>
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">
            <tr>
                <td><label>Show audio player: </label></td><td><input type="checkbox" id="checkedbox" name="audio_show" value="1" <?php if( isset($audio_show)){ checked( '1', $data["audio_show"][0] ); } ?> /></td>	
            </tr>	
            <tr class="audio_product_url">
            	<td><label>Audio URL (*required): <i style="color: #999999;"></i></label><br></td><td><input name="audio_product_url" style="width:500px" value="<?php echo $audio_product_url; ?>" /></td>
            </tr>	
            <tr class="audio_product_url">
            	<td><label>Audio title : <i style="color: #999999;"></i></label><br></td><td><input name="audio_product_title" style="width:500px" value="<?php echo $audio_product_title; ?>" /></td>
            </tr>				
            <tr>
                <td><label>Use video insted of image(you also need to add feautured image): </label></td><td><input type="checkbox" id="checkedbox" name="video_active" value="1" <?php if( isset($video_active)){ checked( '1', $data["video_active"][0] ); } ?> /></td>	
            </tr>	
            <tr class="videoonly">
            	<td><label>Video URL(*required): <i style="color: #999999;">
				<br>Link should look for Youtube: http://www.youtube.com/watch?v=WhBoR_tgXCI - So ID is WhBoR_tgXCI
				<br>Link should look for Vimeo: http://vimeo.com/29017795 so ID is 29017795 <br></i></label><br><input name="video_post_url" style="width:500px" value="<?php echo $video_post_url; ?>" /></td>
            </tr>	
            <tr class="select_video">
            	<td><label>Select video: <i style="color: #999999;">
				<select name="selectv">
				<?php if ($selectv == 'vimeo') {?>
				  <option value="vimeo" selected>Vimeo</option>
				 <?php } else {?>
				  <option value="vimeo">Vimeo</option>						
				 <?php }?>	
				<?php if ($selectv == 'youtube') {?>				 
				  <option value="youtube" selected>YouTube</option>
				 <?php } else {?>
				  <option value="youtube">YouTube</option>						
				 <?php }?>					  
				</select>
				
            </tr>			
            <tr>
                <td><label>Use product short description for hover text: </label></td><td><input type="checkbox" id="checkedbox" name="meta_hover_short" value="1" <?php if( isset($meta_hover_short)){ checked( '1', $data["meta_hover_short"][0] ); } ?> /></td>	
            </tr>	
            <tr class="customhover">
            	<td><label>Custom Hover text: <br><i style="color: #999999;">You can use html tags</i></label><br><?php wp_editor( $meta_post_hover, 'meta_post_hover', array('media_buttons'=>false,'editor_css' => '<style>#meta_post_hover_flshortcodes, #meta_post_hover_woocommerce_shortcodes_button{display:none}</style>') ); ?> </td>
            </tr>				

			
        </table>
		<script>
		jQuery(document).ready(function(){	
				/*video*/
				if (jQuery('input[name=video_active]').is(':checked')){
					jQuery('.videoonly , .select_video').show();}		
				else{
					jQuery('.videoonly, .select_video').hide();}
					jQuery("input[name=video_active]").change(function(){
				if (jQuery('input[name=video_active]').is(':checked')){
					jQuery('.videoonly , .select_video').show();}		
				else{
					jQuery('.videoonly, .select_video').hide();}
				});
				/*hover text*/
				if (jQuery('input[name=meta_hover_short]').is(':checked')){
					jQuery('.customhover').hide();}		
				else{
					jQuery('.customhover').show();}
					jQuery("input[name=meta_hover_short]").change(function(){
				if (jQuery('input[name=meta_hover_short]').is(':checked')){
					jQuery('.customhover').hide();}		
				else{
					jQuery('.customhover').show();}
				});		

				/*audio text*/
				if (jQuery('input[name=audio_show]').is(':checked')){
					jQuery('.audio_product_url').show();}		
				else{
					jQuery('.audio_product_url').hide();}
					jQuery("input[name=audio_show]").change(function(){
				if (jQuery('input[name=audio_show]').is(':checked')){
					jQuery('.audio_product_url').show();}	
				else{
					jQuery('.audio_product_url').hide();}	
				});					
		});
		
		</script>
    </div>
	
      
<?php
	
}
}



if( !function_exists( 'musica_fallback_menu' ) )
{
	/**
	 * Create a navigation out of pages if the user didnt create a menu in the backend
	 *
	 */
	function musica_fallback_menu()
	{
		$current = "";
		if (is_front_page()){$current = "class='current-menu-item'";} 
		
		
		echo "<div class='fallback_menu'>";
		echo "<ul class='musica_fallback menu'>";
		echo "<li $current><a href='".get_bloginfo('url')."'>Home</a></li>";
		wp_list_pages('title_li=&sort_column=menu_order');
		echo "</ul></div>";
	}
}

function getVimeoThumb($id) {
    $data = file_get_contents("http://vimeo.com/api/v2/video/$id.json");
    $data = json_decode($data);
    return $data[0]->thumbnail_small;
}

function removeChar($char){
	$char = explode('#',$char);
	return $char[1];
}

/*audio player*/
function wp_audio_player_head() {
	global $data;	
	
	echo '<script type="text/javascript" src="'.get_template_directory_uri().'/js/audio-player.js"></script>';
	echo '<script type="text/javascript">';
	echo 'AudioPlayer.setup("'.get_template_directory_uri().'/js/player.swf", {';
	echo 'width: 598,animation:"no", bg:"2a2b2c",leftbg:"1e1e20", rightbg:"1e1e20", volslider:"'.removeChar($data['mainColor']).'", voltrack:"ffffff", lefticon:"ffffff",righticon:"ffffff",skip:"ffffff", loader:"'.removeChar($data['mainColor']).'",
		 righticonhover:"ffffff", rightbghover:"'.removeChar($data['mainColor']).'", text:"1e1e20", border:"1e1e20"';
	echo '});</script>';
}
add_action('wp_head','wp_audio_player_head');

function wp_audio_player($atts) {
extract(shortcode_atts(array(
    'no' => rand(0,999),
    'file' => 'http://'
  ), $atts));
	$postmeta = get_post_custom(get_the_id());
	$title = 'Sample title';
	if(isset($postmeta["audio_product_title"][0]))
		$title = $postmeta["audio_product_title"][0];
	if(isset($postmeta["audio_post_title"][0]))
		$title = $postmeta["audio_post_title"][0];	
		
	return '<script type="text/javascript">AudioPlayer.embed("audioplayer_'.$no.'", {soundFile: "'.$file.'",titles: "'.$title.'"});</script><p id="audioplayer_'.$no.'">
			<audio controls="controls">
			<source src="'.$file.'" type="audio/mpeg" />
			Your browser does not support the audio tag.
			</audio>
			</p>';
}
add_shortcode('audio', 'wp_audio_player');

function closeTags($string){
	$output  = '';
	$open = $close = 0;
	$open = substr_count($string , '<strong>');
	$close = substr_count($string , '</strong>');
	if($open > $close )	
		$output .='</strong>'; 
	echo $output;
}

function closeTagsReturn($string){
	$output  = '';
	$open = $close = 0;
	$open = substr_count($string , '<strong>');
	$close = substr_count($string , '</strong>');
	if($open > $close )	
		$output .='</strong>'; 
	return $output;
}

function add_this_script_footer(){ 
	global $data, $sitepress;
	
		if (!function_exists('icl_object_id') or (ICL_LANGUAGE_CODE == $sitepress->get_default_language()) ) { 
			$search = stripText($data['translation_enter_search']); 
			
			} 
		else {  
			$search = __('Enter search...','wp-musica'); 
				
		} 

if($data['add_to_cart'] == 1){
?>

<script>
	jQuery(document).ready(function(){	
		jQuery('.add_to_cart_button').live('click', function() {
			jQuery('html, body').animate({scrollTop:0}, 'medium',function(){ 

			
				jQuery('.cartHide').animate({opacity : 0},300);
				setTimeout(function() {
				  jQuery('.cart-bubble-load').addClass('loading'); 
				}, 300); 	
				setTimeout(function() {
				  	jQuery('.cart-bubble-load').removeClass('loading');  
				}, 2300);	
				setTimeout(function() {
				  	jQuery('.cartHide').animate({opacity : 1},300);
					jQuery('.widget_shopping_cart_top').css('position','static');
				}, 2300);				
			
			});
		});
	});
</script>
<?php } ?>
<script>	
	jQuery(document).ready(function(){	
		jQuery('#sidebarsearch input').val('<?php echo $search ?>');
		
		jQuery('#sidebarsearch input').focus(function() {
			jQuery('#sidebarsearch input').val('');
		});
		
		jQuery('#sidebarsearch input').focusout(function() {
			jQuery('#sidebarsearch input').val('<?php echo $search ?>');
		});	
		
	});	
	

	

</script>
<?php  }


add_action('wp_footer', 'add_this_script_footer'); 	



add_filter( 'the_category', 'add_nofollow_cat' );  

function add_nofollow_cat( $text ) { 
	$text = str_replace('rel="category tag"', "", $text); 
	return $text; 
	}


?>